"""Rule 2 - Pre-load a global into a named local before dividing.

## Trigger

Watcom emits one of two divide setups for ``dst = g / k`` where
``g`` is a global and ``k`` is a constant:

| Form                                                | Setup        |
|-----------------------------------------------------|--------------|
| ``dst = g / k;``                                    | EDX-first    |
| ``int r = g / k; dst = r; helper(r, 1);``           | EAX-first    |
| ``int t = g; int r = t / k; dst = r; helper(r, 1);``| EDX-first    |

  * **EDX-first** (PS.EXE’s shape): ``mov edx, [g]; mov ebx, k;
     mov eax, edx; sar edx, 31; idiv ebx``.
  * **EAX-first**: ``mov ebx, k; mov eax, [g]; mov edx, eax;
     sar edx, 31; idiv ebx``.

The trigger for EAX-first is: the divide-result temp is consumed
by a subsequent function call.  At that point the result has more
uses than just the immediate store, and the cost-driven scheduler
emits the divisor first (so EBX is set up before EAX is
consumed by the divide), saving 1 byte via the special
``mov eax, [imm32]`` 5-byte opcode ``a1`` (vs ``mov edx,
[imm32]`` = 6-byte ``8b 15 …``).

The **fix** when PS.EXE shows EDX-first but recomp emits
EAX-first: hoist the dividend into a named local just before the
divide — ``int t = g; r = t / k;``.  That forces ``t`` through
``temps.c``’s per-temp allocation and lands the dividend on EDX,
putting the EDX-first shape back regardless of the result’s
downstream use.  The fix costs one byte (the
``a1`` → ``8b 15`` swap) but matches PS.EXE.

## Mechanism

``RG_DBL_DIV`` in ``bld/cg/intel/386/h/rg.h:63`` constrains the
dividend to the ``EDX:EAX`` pair and the divisor to any 32-bit
reg.  The optab in ``bld/cg/intel/386/c/386table.c:728`` routes
``ANY, C`` (memory or register dividend, constant divisor) through
``R_MOVOP2TEMP`` first, then ``R, C`` is generated by ``G_DIV2``.

Writing ``int t = g;`` as a separate statement materialises ``t``
as a named ``T_PSEUDO`` temp.  ``temps.c``’s per-temp pipeline
routes it through the savings-sorted ``AssignARegister`` path
(``bld/cg/c/regalloc.c:1034``).  EAX is reserved for the divide
result, so the next preference in ``Reg64Order`` (which after
EAX is EBX, but EBX is occupied by the divisor, so EDX) lands
on ``t``.  Without the named local, the result-temp’s
live-across-call lifetime is what dominates the savings score,
pushing the dividend onto EAX directly so EBX is free as a
result stash.
"""

from __future__ import annotations

import pytest

from c2.commands.oracle import compile_snippet


# ---- Source variants -----------------------------------------------------

_HELPER_DECL = "extern int helper(int x, int y);\n"
_HELPER_DEF = "int helper(int x, int y) { (void)x; (void)y; return 0; }\n"
_GLOBALS = "extern int g, dst;\n"


_BARE_DIVIDE = _GLOBALS + """\
void f(void) { dst = g / 10; }
"""

_DIVIDE_WITH_DOWNSTREAM_USE = _GLOBALS + _HELPER_DECL + """\
void f(void) {
    int r = g / 10;
    dst = r;
    dst = helper(r, 1);
}
"""

_DIVIDE_PRELOADED = _GLOBALS + _HELPER_DECL + """\
void f(void) {
    int t = g;
    int r = t / 10;
    dst = r;
    dst = helper(r, 1);
}
"""

_DEFS = "int g; int dst;\n" + _HELPER_DEF


# ---- Helpers --------------------------------------------------------------


def _compile(source, image):
    b = compile_snippet(source, image=image, extern_defs=_DEFS)
    assert b.ok, f"build failed:\n{b.output}"
    return b.function("f")


def _idiv_setup(fn):
    """Return (load_idx, set_imm_idx, idiv_idx) for the divide region."""
    seq = [(i.mnemonic, i.op_str) for i in fn.insns]
    idiv_idx = next(k for k, (m, ops) in enumerate(seq)
                    if m == "idiv" and ops == "ebx")
    load_idx = None
    set_imm_idx = None
    for k in range(idiv_idx - 1, max(-1, idiv_idx - 6), -1):
        m, ops = seq[k]
        if m == "mov" and ops.startswith("ebx, ") and "ptr" not in ops:
            set_imm_idx = k
        elif m == "mov" and "dword ptr" in ops and (
            ops.startswith("eax,") or ops.startswith("edx,")
        ):
            load_idx = k
    assert load_idx is not None, fn.disasm_text()
    assert set_imm_idx is not None, fn.disasm_text()
    return load_idx, set_imm_idx, idiv_idx


# ---- Tests ----------------------------------------------------------------


def test_bare_divide_is_edx_first(watcom_10_0a):
    """A bare ``dst = g / 10;`` emits EDX-first (no downstream consumer)."""
    fn = _compile(_BARE_DIVIDE, watcom_10_0a)
    load, imm, idiv = _idiv_setup(fn)
    assert load < imm, f"expected mov edx,[g] BEFORE mov ebx,imm:\n{fn.disasm_text()}"
    assert fn.has_insn("mov", "edx, dword ptr"), fn.disasm_text()
    assert fn.has_insn("mov", "eax, edx"), fn.disasm_text()
    # And no EAX load from memory.
    assert not fn.has_insn("mov", "eax, dword ptr"), fn.disasm_text()


def test_inline_divide_with_downstream_use_is_eax_first(watcom_10_0a):
    """``int r = g / 10; ...; helper(r, 1)`` flips to EAX-first.

    The result temp is consumed by ``helper`` so the savings score
    favours the EAX-direct load, saving 1 byte via the ``a1`` opcode.
    """
    fn = _compile(_DIVIDE_WITH_DOWNSTREAM_USE, watcom_10_0a)
    load, imm, idiv = _idiv_setup(fn)
    assert imm < load, f"expected mov ebx,imm BEFORE the load:\n{fn.disasm_text()}"
    assert fn.has_insn("mov", "eax, dword ptr"), fn.disasm_text()


def test_preloaded_divide_is_edx_first(watcom_10_0a):
    """``int t = g; int r = t / 10;`` flips to EDX-first."""
    fn = _compile(_DIVIDE_PRELOADED, watcom_10_0a)
    load, imm, idiv = _idiv_setup(fn)
    assert load < imm, f"expected mov edx,[g] BEFORE mov ebx,imm:\n{fn.disasm_text()}"
    assert fn.has_insn("mov", "edx, dword ptr"), fn.disasm_text()
    assert fn.has_insn("mov", "eax, edx"), fn.disasm_text()
    # And no EAX load from memory.
    assert not fn.has_insn("mov", "eax, dword ptr"), fn.disasm_text()


def test_preload_costs_exactly_one_byte(watcom_10_0a):
    """EDX-first costs one byte more than EAX-first (5b a1 -> 6b 8b 15)."""
    inline = _compile(_DIVIDE_WITH_DOWNSTREAM_USE, watcom_10_0a)
    preload = _compile(_DIVIDE_PRELOADED, watcom_10_0a)
    delta = preload.size() - inline.size()
    assert delta == 1, (
        f"expected +1 byte for preloaded form; got {delta}\n"
        f"--- INLINE ({inline.size()}b) ---\n{inline.disasm_text()}\n"
        f"--- PRELOAD ({preload.size()}b) ---\n{preload.disasm_text()}"
    )


def test_all_variants_use_signed_idiv_with_sar_31(watcom_10_0a):
    """Sanity: every variant emits ``idiv ebx`` with sign-extension."""
    for source, label in [
        (_BARE_DIVIDE, "bare"),
        (_DIVIDE_WITH_DOWNSTREAM_USE, "inline"),
        (_DIVIDE_PRELOADED, "preload"),
    ]:
        fn = _compile(source, watcom_10_0a)
        assert fn.has_insn("idiv", "ebx"), f"{label}: {fn.disasm_text()}"
        assert fn.has_insn("sar", ", 0x1f") or fn.has_insn("sar", ", 31"), (
            f"{label}: missing sar reg, 31\n{fn.disasm_text()}"
        )
