#ifndef C2_FUNCS_H
#define C2_FUNCS_H

/* Auto-generated — do not edit. Run: uv run c2 gen-header */
/* Optional canonical function prototypes.  Do not include this layer
 * blindly when matching PS.EXE call-site prototype visibility. */

#include "c2_types.h"

/* ── Function externs (from decomp/src/*.c definitions) ── */

/* Functions are emitted only when their definition signature
   matches every per-file forward declaration that references
   them.  Conflicts are listed in the section below — fix the
   stub or the forward decl manually, then regenerate. */

extern void Bresenham_decision(int mode);
extern short DecodeChar(void);
extern short DecodePosition(void);
extern void DeleteNode(short p);
extern void EncodeChar(unsigned short c);
extern void EncodeEnd(void);
extern void EncodePosition(unsigned short c);
extern short GetBit(void);
extern int GetByte(void);
extern void InitTree(void);
extern void InsertNode(short r);
extern void Putcode(short l, unsigned short c);
extern void StartHuff(void);
extern void __smackw32_text_pad1(void);
extern void __smackw32_text_pad2(void);
extern void a01_cohort(void);
extern void a02_enemy(void);
extern void a04_raider(void);
extern void a05_revolt(void);
extern void a06_roman_ship(void);
extern void a08_raider_ship(void);
extern void act_about(void);
extern void act_adjust_down(void);
extern void act_adjust_up(void);
extern void act_aquaduct(void);
extern void act_army_box_help(void);
extern void act_army_wage_down(void);
extern void act_army_wage_up(void);
extern void act_back_to_front_panel(void);
extern void act_back_tutorial_page(void);
extern void act_barracks(void);
extern void act_baths(void);
extern void act_battle_autocalc(void);
extern void act_battle_help(void);
extern void act_battle_retreat(void);
extern void act_battle_select_all(void);
extern void act_battle_surrender(void);
extern void act_business(void);
extern void act_cancel_file_op(void);
extern void act_census(void);
extern void act_choose_init_region(void);
extern void act_choose_name(void);
extern void act_clear(void);
extern void act_clear_rm(void);
extern void act_conscription_down(void);
extern void act_conscription_up(void);
extern void act_correct_map(void);
extern void act_demob_cohort(void);
extern void act_detailed_query(void);
extern void act_do_exit(void);
extern void act_do_file_op(void);
extern void act_do_year_end(void);
extern void act_donation(void);
extern void act_donation_down(void);
extern void act_donation_up(void);
extern void act_dont_exit(void);
extern void act_dos(void);
extern void act_down_directory(void);
extern void act_education(void);
extern void act_entertainment(void);
extern void act_exclaim(void);
extern void act_exit_and_save(void);
extern void act_exit_game(void);
extern void act_exit_help(void);
extern void act_exit_turbo_mode(void);
extern void act_final_bribe(void);
extern void act_forum(void);
extern void act_forums(void);
extern void act_forward_tutorial_page(void);
extern void act_fountain(void);
extern void act_game_speed(void);
extern void act_gardens(void);
extern void act_gardens_plaza(void);
extern void act_general_query(void);
extern void act_gift_down(void);
extern void act_gift_send(void);
extern void act_gift_up(void);
extern void act_goto_city(void);
extern void act_goto_city_map(void);
extern void act_goto_flags(void);
extern void act_goto_message(void);
extern void act_goto_prov_map(void);
extern void act_health(void);
extern void act_help_game(void);
extern void act_help_history(void);
extern void act_help_icons(void);
extern void act_help_tips(void);
extern void act_history_graph_longer(void);
extern void act_history_graph_shorter(void);
extern void act_hospital(void);
extern void act_house1(void);
extern void act_house2(void);
extern void act_house3(void);
extern void act_house4(void);
extern void act_house5(void);
extern void act_houses(void);
extern void act_ind_tax_down(void);
extern void act_ind_tax_up(void);
extern void act_industries(void);
extern void act_init_turbo_mode(void);
extern void act_less_mercs(void);
extern void act_load_game(void);
extern void act_market(void);
extern void act_middle_tutorial_page(void);
extern void act_more_mercs(void);
extern void act_move_unit(void);
extern void act_new_game(void);
extern void act_next_cohort(void);
extern void act_no(void);
extern void act_nof_samples(void);
extern void act_order_cohort(void);
extern void act_out(void);
extern void act_ov_admin(void);
extern void act_ov_education(void);
extern void act_ov_entertainment(void);
extern void act_ov_geography(void);
extern void act_ov_health(void);
extern void act_ov_industry(void);
extern void act_ov_landval(void);
extern void act_ov_security(void);
extern void act_ov_unrest(void);
extern void act_ov_water(void);
extern void act_pause(void);
extern void act_pause_help(void);
extern void act_people_query(void);
extern void act_plaza(void);
extern void act_pop_tax_down(void);
extern void act_pop_tax_up(void);
extern void act_prefecture(void);
extern void act_preload(void);
extern void act_prev_cohort(void);
extern void act_query(void);
extern void act_query_do_help(int delta);
extern void act_query_help(void);
extern void act_query_history(void);
extern void act_query_mode(void);
extern void act_query_tips(void);
extern void act_request_down(void);
extern void act_request_up(void);
extern void act_resevoir(void);
extern void act_review_in_10(void);
extern void act_review_in_25(void);
extern void act_rewind_help(void);
extern void act_rm_farm(void);
extern void act_rm_fort(void);
extern void act_rm_industry(void);
extern void act_rm_mine(void);
extern void act_rm_port(void);
extern void act_rm_quarry(void);
extern void act_rm_security(void);
extern void act_rm_shipyard(void);
extern void act_rm_trading_post(void);
extern void act_rm_warehouse(void);
extern void act_rm_workhouse(void);
extern void act_road(void);
extern void act_road_rm(void);
extern void act_rotate_anticlockwise(void);
extern void act_rotate_clockwise(void);
extern void act_salary_down(void);
extern void act_salary_up(void);
extern void act_samples_level(void);
extern void act_save_game(void);
extern void act_scroll_speed(void);
extern void act_security(void);
extern void act_select_arena(void);
extern void act_select_cancel(void);
extern void act_select_circus(void);
extern void act_select_circus_max(void);
extern void act_select_colosseum(void);
extern void act_select_farm(void);
extern void act_select_grammaticus(void);
extern void act_select_large_forum(void);
extern void act_select_large_temple(void);
extern void act_select_library(void);
extern void act_select_medium_forum(void);
extern void act_select_medium_temple(void);
extern void act_select_odium(void);
extern void act_select_ov_map(void);
extern void act_select_rhetor(void);
extern void act_select_small_forum(void);
extern void act_select_small_temple(void);
extern void act_select_theatre(void);
extern void act_send_donation(void);
extern void act_send_gift(void);
extern void act_set_marker1(void);
extern void act_set_marker2(void);
extern void act_set_marker3(void);
extern void act_set_patrol_markers(void);
extern void act_set_patrol_stop(void);
extern void act_set_return_home(void);
extern void act_set_skill_levels(void);
extern void act_set_slaves_to_need_level(int kind);
extern void act_set_temple_tips(int tip_kind);
extern void act_show_ov_legend(void);
extern void act_skill_down(void);
extern void act_skill_up(void);
extern void act_slave_city_road_down(void);
extern void act_slave_city_road_up(void);
extern void act_slave_city_wall_down(void);
extern void act_slave_city_wall_up(void);
extern void act_slave_city_water_down(void);
extern void act_slave_city_water_up(void);
extern void act_slave_fire_down(void);
extern void act_slave_fire_up(void);
extern void act_slave_reg_upkeep_down(void);
extern void act_slave_reg_upkeep_up(void);
extern void act_slave_reg_work_down(void);
extern void act_slave_reg_work_up(void);
extern void act_slave_welfare_down(void);
extern void act_slave_welfare_up(void);
extern void act_start_help(void);
extern void act_stop_go(void);
extern void act_swap_maps(void);
extern void act_take_promotion(void);
extern void act_target_unit(void);
extern void act_temple(void);
extern void act_test(void);
extern void act_tog_ambients(void);
extern void act_tog_anims(void);
extern void act_tog_autosave(void);
extern void act_tog_peace(void);
extern void act_tog_samples(void);
extern void act_tog_speech(void);
extern void act_tog_tunes(void);
extern void act_tog_yearend(void);
extern void act_toggle_anims(void);
extern void act_toggle_sound_fx(void);
extern void act_toggle_tunes(void);
extern void act_toggle_year_end(void);
extern void act_tower(void);
extern void act_tunes_level(void);
extern void act_turbo(void);
extern void act_tutorial(void);
extern void act_undo_cm(void);
extern void act_unit_column_formation(void);
extern void act_unit_line_formation(void);
extern void act_unit_mop_up_formation(void);
extern void act_unit_tortoise_formation(void);
extern void act_up_directory(void);
extern void act_wall(void);
extern void act_wall_rm(void);
extern void act_water(void);
extern void act_well(void);
extern void act_yes(void);
extern void act_zoom_in(void);
extern void act_zoom_level1(void);
extern void act_zoom_level2(void);
extern void act_zoom_out(void);
extern void action(void);
extern void adjust(int kind, int *var, int step, int max, int min, int x, int y, int mode);
extern void adjust_culture_criteria(void);
extern void adjust_empire_criteria(void);
extern void adjust_peace_criteria(void);
extern void adjust_proserity_criteria(void);
extern void adjust_regions_coastline(int x, int y, int width, int height);
extern void adjust_sailable_area(void);
extern void adjust_slave_usage(void);
extern char affected_by_cover1(unsigned char *p, int range, char mask);
extern char affected_by_cover2(unsigned char *p, int range, char mask);
extern int allow_samples(void);
extern int allowed_keys(void);
extern int alter_slave_reqs(int kind, int delta);
extern int any_army_building_adjusts(void);
extern int aquaduct_ramifications(int x, int y);
extern int are_overlays_on(void);
extern int are_smacking(void);
extern void army_building_adjusts(void);
extern void army_intelligence(void);
extern void army_restoring_adjusts(void);
extern void arrow_intelligence(void);
extern int arrow_off_map(void);
extern void arrow_update(void);
extern void assign_to_new_province(void);
extern int at_edge_of_map(int x, int y);
extern void auto_conquer(void);
extern void background_screen(void);
extern void backtrack_figure(int fig);
extern int barbarian_in_region(int dirc, int from_sea);
extern int barbarian_invades_city(int army_idx);
extern void barbarians_drop_by_city(int dirc, int count);
extern void basic_empire_screen(void);
extern void basic_inf_settings(void);
extern void basic_temple_screen(void);
extern void battle_action(void);
extern void battle_auto_resolve(void);
extern void battle_game_loop(void);
extern void battle_intro(void);
extern void battle_intro_game_loop(void);
extern void battle_outtro(void);
extern void battle_screen(int skipblackout);
extern void battle_stats_panel(void);
extern void battle_totals_panel(void);
extern void battle_tune_mood_from_type(int unit_no);
extern void bd(int axis);
extern int big_random(void);
extern void black_out(void);
extern void bottom2_line_no_sides(void);
extern void bottom2_line_with_sides(void);
extern void bottom3_line_no_sides(void);
extern void bottom3_line_with_sides(void);
extern void bottom_line_no_sides(void);
extern void bottom_line_with_sides(void);
extern void bribe_emperor(void);
extern void build_an_area(int x1, int y1, int x2, int y2, int base_kind, int edge_bits, int color);
extern void build_aquaduct_from_elastic(void);
extern void build_city_item(void);
extern void build_reg_road_from_elastic(void);
extern void build_reg_wall_from_elastic(void);
extern void build_region_item(void);
extern void build_road_from_elastic(void);
extern void build_units_figures(int made, int kind, int sub_kind, int sub_kind2, int slot, int stance, int player, int target_men, int cols, int row_count, unsigned char *fig_a, unsigned char *fig_b, int stage_slot);
extern void build_wall_from_elastic(void);
extern void business_output(int col, int y);
extern void cap_land_value(int rows);
extern void capture_shot(char *fname);
extern void cd_path(const char *fname);
extern int chance_of_attack(int trouble_type, int months_since, int probe_only, int p4);
extern void change_citizen_targs(int delta);
extern void change_house(int n, int size, int variant);
extern void change_lv(int x, int y, int radius, int extra, int delta);
extern void change_reg_sized(int rm_byte, int color, int size, int rm_offset);
extern void change_sized(int bk, int color, int size, int sptr);
extern signed char check_anti_ferret_move(signed char dir);
extern void check_army_list(void);
extern void check_citizen_list(void);
extern signed char check_clock_ferret_move(signed char dir);
extern int check_file_exists(char *fname);
extern int check_for_Trident(void);
extern int check_for_Tseng(void);
extern int check_for_free_slot(void);
extern void check_for_promotion(void);
extern void check_game_over(void);
extern void check_goods_in_region_warehouses(void);
extern int check_highlight_list(short idx);
extern int check_old_sslots(char *fname);
extern void check_region_map_for_farm_square(int x, int y, char mask);
extern void check_region_map_for_port_square(int x, int y);
extern int check_selection_goods_list(short val);
extern void check_viewed_cohort(void);
extern int choose_from(struct choice_rec *records, int count);
extern void choose_odd_tune(int x);
extern int citizen_go_to_target(int kind);
extern void citizen_intelligence(void);
extern int citizen_maraude_to_target(int kind);
extern int city_icon_allowed(int idx);
extern void city_map_screen(int do_black_out);
extern int city_pop_limit_10_to_1(int value, int factor);
extern int city_test_for_road(int x, int y, int map_ref, int world_dir);
extern void citymap_evolution(void);
extern void clear_a_reg_area(int x0, int y0, int x1, int y1, int keep_fortress);
extern void clear_a_screen(void);
extern void clear_all_bm(char layer);
extern void clear_all_cm(char layer);
extern void clear_all_highlights_from_battlemap(void);
extern void clear_all_rm(char layer);
extern void clear_all_screens(void);
extern void clear_an_area(int x1, int y1, int x2, int y2);
extern void clear_army(struct army_rec *p);
extern void clear_army_from_fort_ref(int ref);
extern void clear_army_list(void);
extern void clear_arrow(struct arrow_rec *p);
extern void clear_arrow_list(void);
extern void clear_basic(int sptr);
extern void clear_battle_gfx_buffers(void);
extern void clear_citizen(struct citizen_rec *p);
extern void clear_citizen_list(void);
extern void clear_city_flag(int val);
extern void clear_danger_flag(void);
extern void clear_edge_info(void);
extern void clear_empire(void);
extern void clear_ferret_map(int margin, unsigned char *map_base, int map_wi, int map_hi, int cell_size, int x1, int y1, int x2, int y2);
extern void clear_figure(struct figure_rec *p);
extern void clear_figure_list(void);
extern void clear_fire_zones(void);
extern void clear_highlight_goods_list(void);
extern void clear_huts(void);
extern void clear_keys(void);
extern void clear_landfill(void);
extern void clear_map_gfx_buffers(void);
extern void clear_messages(void);
extern void clear_mouse(void);
extern void clear_prov_flag(int val);
extern void clear_reg_basic(int rm_offset);
extern void clear_region_ferret_map(int mode, int margin, unsigned char *map_base, int map_wi, int map_hi, int cell_size, int x1, int y1, int x2, int y2);
extern void clear_region_map(void);
extern void clear_screens(void);
extern void clear_sea_ferret_map(int unused, int margin, unsigned char *map_base, int map_wi, int map_hi, int cell_size, int x1, int y1, int x2, int y2);
extern void clear_sized_to_reg_basic(int rm_offset, int size);
extern void clear_sized_to_rubble(int sptr, int size, int rubble_kind);
extern void clear_to_empty(int sptr);
extern void clear_to_rubble(int sptr, int rubble_kind);
extern void clear_unit(struct unit_rec *p);
extern void clear_unit_list(void);
extern void click_delay(int delay);
extern void click_on_text(int x, int y, int w, int h);
extern void click_warning(int what, int x, int y);
extern int clicked_delay(int delay);
extern void clip_battle_zoom_level2(void);
extern void clip_map_bottom(void);
extern void clip_zoom_level1(void);
extern void collect_ind_tax(void);
extern void collect_pop_tax(void);
extern void confirm(int what, int x, int y);
extern int confirm_fire_target(void);
extern void continue_battle(int pre_loaded);
extern void continue_db(void);
extern int continue_smacking(int p1, int x, int mode);
extern int control_buttons(int x, int y, struct button_rec *buttons, int count);
extern int control_icons(struct icon_rec *icons, int count);
extern int control_menus(struct menu_rec *menus, int count, void (*show_map_fn)(void));
extern int control_selection(struct selection_rec *list, int count, int x, int y, int what);
extern void convert256_to_256xscreen(unsigned char *src, unsigned char *dst);
extern void convert256x_to_256screen(char *src, char *dst);
extern int convert_lbm_file(unsigned char *src, unsigned char *dst, char *pal, int length);
extern void copy_fb(char *src, char *dst);
extern void copy_ferret_run_to_army(void);
extern void copy_ferret_run_to_citizen(void);
extern void copy_palette(char *src, char *dst);
extern void copy_to_physical_screen(int p1, int p2);
extern void count_city_flags(void);
extern void count_danger_flags(void);
extern void count_prov_flags(void);
extern void cover_mouse_droppings(void);
extern int create_army(int type, int x, int y, char mode);
extern int create_arrow(unsigned char *arrow_data_ptr, int owner, int sx, int sy, int ex, int ey);
extern int create_citizen(int type, int x, int y, char is_barb);
extern int create_figure(int sprite_type, int base_x, int off_x, int base_y, int off_y, int owner, int unit_no);
extern int create_unit(int owner, int x, int y, int type);
extern void cycle_colours(int start_idx, int end_idx);
extern void de_install_mouse(void);
extern void de_toggle_all_icons(struct icon_rec *icons, int count);
extern void deal_with_battles(void);
extern void debug_screen(void);
extern void del_fb(void);
extern void deselect_all_figures(void);
extern void deselect_enemy_figures(void);
extern void destroy_an_atom(int sptr, int rubble_kind);
extern void destroy_reg_atom(int sptr);
extern void devolve_a_building(int count, int size, unsigned char kind, unsigned char color_base, unsigned char color_step);
extern int devolve_a_house(int n);
extern void display_picfile(char *fname);
extern int display_pl8file(char *pl8_fname, char *pal_fname);
extern void do_32_count(void);
extern void do_a_tutorial_page(void);
extern void do_act_zoom_in(int decayed);
extern void do_act_zoom_out(int decayed);
extern void do_battle_victory(void);
extern void do_delay(int n);
extern void do_fight_battle(int continuing);
extern void do_heavy_ai(void);
extern void do_land_trade(int kind, int p2, int x, int y);
extern void do_light_ai(void);
extern void do_lose_game(void);
extern void do_neg(void);
extern void do_pos(void);
extern void do_promotion(int level);
extern int do_sea_trade(int compass_side, int cargo, int home_x, int home_y, int army_id);
extern void do_svga_smacked_anim(char *fname);
extern void do_the_fight(void);
extern void do_tutorial(void);
extern void do_vga_smacked_anim(char *fname);
extern int dock_the_ship_in_good_port(int heading);
extern void donation_game_loop(void);
extern void dos_cls(void);
extern void down_slider_var(struct slider_rec *s);
extern void draw_a_2point(int x, int y, int colour);
extern void draw_a_box(int x, int y, int w, int h, int colour);
extern void draw_a_diamond(int x, int y, int width, int height, int colour);
extern void draw_a_dias(int x, int y, int w, int h);
extern void draw_a_dotted_line(int x1, int y1, int x2, int y2, int colour);
extern void draw_a_line(int x1, int y1, int x2, int y2, int colour);
extern void draw_a_point(int x, int y, int colour);
extern void draw_a_rect(int x, int y, int w, int h, int colour);
extern void draw_battle_part(int n);
extern void draw_city_map_part(int n);
extern void draw_region_map_part(int n);
extern void drop_all_units_morale(int match_type, int delta_a, int delta_b);
extern int edit_format_buffer(void);
extern void elephant_ai(void);
extern void elephant_fire(void);
extern int empire_in_region(int dirc, int from_sea);
extern void employment(void);
extern int entering_new_square(void);
extern int evacuate(unsigned char *src, unsigned char *dst);
extern void evolve_a_building(int count, int size, unsigned char kind, unsigned char color_base, unsigned char color_step);
extern void evolve_a_cm_row(void);
extern int evolve_a_house(int n);
extern void evolve_a_plaza(signed char value, signed char old_kind, int x);
extern void evolve_amenity_cover(int rows);
extern void evolve_fort_activity(int rows);
extern void evolve_forum_activity(int rows);
extern void evolve_industrial_activity(int rows);
extern void evolve_land_value(int rows);
extern void evolve_region(int rows);
extern void evolve_security_activity(int rows);
extern void evolve_security_cover(int rows);
extern void evolve_to_current_fabric(void);
extern void evolve_water_supply_baths_industry(int rows);
extern void evolve_water_table(int rows);
extern void exit_game(void);
extern void exit_game_loop(void);
extern int exit_screen(void);
extern int exit_screen_at(int x, int y);
extern void explain_forum(void);
extern void extended_confirm(int what, int x, int y);
extern void f01_regular(void);
extern void f02_irregular(void);
extern void f05_barb_sword(void);
extern void f06_barb_spear(void);
extern void f07_barb_axe(void);
extern void f08_barb_pike(void);
extern void f11_barb_horse_heavy(void);
extern void f14_barb_camel(void);
extern void f15_barb_elephant(void);
extern void f16_barb_bow(void);
extern void f17_barb_knife(void);
extern void fade_sequence_in(int idx);
extern void fade_sequences_out(int idx);
extern void fade_to_black_out(void);
extern void fade_to_palette(char *p);
extern void fade_to_temp_palette(char *fname);
extern unsigned char ferret_heading(int x, int y);
extern void fight_barbarian(int idx);
extern void fight_centurian(int idx);
extern int figure_go_to_target(void);
extern void figure_images(void);
extern void figure_intelligence(void);
extern void figure_update(void);
extern void fill_cohort_centuries(void);
extern void fill_warehouses_with(int x, int y, int amount, int goods, int refresh);
extern int find_adjacent_target(void);
extern void find_attack_spot(void);
extern void find_defensive_spot(void);
extern int find_enemy(int cx, int cy, int r);
extern int find_figure(int mode);
extern int find_invading_army(int cx, int cy, int r);
extern int find_nearest_enemy(void);
extern int find_nearest_target(int max_dist);
extern void fire_trouble(void);
extern void fix_plyr_name(char *buf);
extern void flag_mode_action(void);
extern void flag_range(int extra, int x, int y, int range, unsigned char field_off, unsigned char mask);
extern void flag_range3(int extra, int x, int y, int range, int unused_field_off, unsigned char threshold, unsigned char query_mask, unsigned char clear_mask);
extern void flag_rm_area(int x, int y, int size, char mask_byte);
extern void flesh_river_atoms(void);
extern void floop_end(void);
extern void flush_sb_buffer(void);
extern void fly_to_target(void);
extern void font_centre(int idx, int word_count, int x_left, int arg4, int total_width, unsigned char *font, int p7);
extern void font_format_split(int idx, int word_skip, int x, int y_start, int max_width, int line_limit, int x_overflow, int max_width_overflow, unsigned char *font, int color);
extern void font_list(int idx, int word_count, int x, int y, unsigned char *font, int color);
extern void font_no(int value, char pad_char, char *suffix, int x, int y, unsigned char *font, int color);
extern void forum_admin_game_loop(void);
extern void forum_admin_screen(void);
extern void forum_advisor_game_loop(void);
extern void forum_advisor_screen(void);
extern void forum_army_game_loop(void);
extern void forum_army_screen(void);
extern void forum_career_game_loop(void);
extern void forum_career_screen(void);
extern void forum_city_only_screen(void);
extern void forum_clerks_game_loop(void);
extern void forum_clerks_screen(void);
extern void forum_constant_screen(void);
extern void forum_empire_game_loop(void);
extern void forum_empire_screen(void);
extern void forum_empty_screen(void);
extern void forum_explanations(int idx, int hilite);
extern void forum_game_loop(void);
extern void forum_idle_game_loop(void);
extern void forum_industry_game_loop(void);
extern void forum_industry_screen(void);
extern void forum_rome_game_loop(void);
extern void forum_rome_screen(void);
extern void forum_slaves_game_loop(void);
extern void forum_slaves_screen(void);
extern void forum_temple_game_loop(void);
extern void forum_temple_screen(void);
extern void forum_update_census(void);
extern void four_by_four(int x, int y);
extern void free_pumping_memory(void);
extern void free_sample_buffer(int n);
extern void free_scratch_buffer(void);
extern void free_up_sslot(int slot);
extern int game_speed(void);
extern void garden_an_area(int x1, int y1, int x2, int y2);
extern int general_business_cause(void);
extern void general_reform(int p1);
extern void general_sprite(int idx, int x, int y);
extern void generate_battle_map(void);
extern void generate_city_map_geography(void);
extern int generate_cm_river(void);
extern void generate_cm_scrub(void);
extern int get_a_shootable_unit(void);
extern int get_a_unit_centered_on_mouse(void);
extern int get_actual_viewed_army(void);
extern void get_admin_ov_image(void);
extern void get_allowed_selections(struct selection_rec *list, int count, int what);
extern int get_aqua_start_node(int x, int y);
extern int get_aqua_web(int x, int y);
extern void get_aquaduct_elastic(void);
extern int get_army_name_from_fort_ref(int ref);
extern void get_army_ship_image(int img_base);
extern void get_army_totals(void);
extern int get_army_walk_dirc(int dir, int rot);
extern void get_arrow_base_image(void);
extern int get_attackers(int dir, int scan_all);
extern void get_average_ind_tax(void);
extern void get_average_pop_tax(void);
extern void get_barbarian_image(void);
extern void get_battle_centuries_left(void);
extern void get_battle_men(void);
extern void get_battle_mood(void);
extern void get_battle_odds(void);
extern void get_best_elastic_value(int x, int y, int ptr, int dirc);
extern int get_best_lv(unsigned char *base, int bp);
extern void get_best_rm_elastic_value(int x, int y, int ptr, int dirc);
extern int get_border_position(int x, int y, int trader_is);
extern int get_buffer_ofset(int idx);
extern void get_census(int quiet);
extern void get_circus_bodge(unsigned char kind);
extern void get_city_mood(void);
extern int get_closest_trading_post(int x, int y, int radius);
extern void get_cohort_image(void);
extern void get_cohorts_in_action(void);
extern void get_contenders(void);
extern void get_current_cohort_totals(void);
extern void get_dirc_from_army_wf_run(void);
extern void get_dirc_from_citizen_wf_run(void);
extern void get_directory(char *pattern);
extern int get_distance(int x1, int y1, int x2, int y2);
extern void get_dos_memory(void);
extern void get_education_ov_image(void);
extern void get_enemy_image(void);
extern void get_entertainment_ov_image(void);
extern void get_estimates(void);
extern void get_fb_length(void);
extern int get_fb_lines(void);
extern int get_fb_width(unsigned char *font);
extern unsigned char get_ferret2(int dir);
extern void get_fig_death_image(void);
extern void get_fig_fight_image(void);
extern void get_fig_in_unit_position(int mode, int p2, int fig_idx);
extern void get_fig_missile_image(void);
extern void get_fig_still_image(void);
extern void get_fig_tortoise_image(void);
extern void get_fig_walk_image(void);
extern void get_filename_extension(const char *fname);
extern char get_filename_length(char *s);
extern void get_fire_cover(void);
extern int get_fire_target(int fig_no);
extern void get_free_memory(void);
extern void get_general_sprite_sizes(int sprite_index);
extern void get_health_ov_image(void);
extern void get_highlight_position(void);
extern int get_history_from_buffer(int *buf, int row, int col);
extern void get_history_in_buffer(int *buf);
extern void get_icon_over(void);
extern int get_incomplete_node(int row_stride, int cell_stride);
extern void get_ind_tax_estimate(void);
extern void get_industry_growth_factor(void);
extern void get_industry_ov_image(void);
extern char get_insert_letter(void);
extern void get_insurrection_factor(void);
extern void get_key(void);
extern void get_landfill(int evolve);
extern void get_landval_ov_image(void);
extern int get_letter_width(int letter, unsigned char *font);
extern int get_linked_page(void);
extern int get_longest_distance(int x1, int y1, int x2, int y2);
extern void get_longest_side(int x1, int y1, int x2, int y2);
extern void get_morale_and_readiness(void);
extern void get_mouse(void);
extern void get_mouse_droppings(void);
extern void get_movement_image(int img_base);
extern int get_nearest_army_to_track(int x, int y);
extern int get_nearest_enemy_to_track(int x, int y);
extern int get_nearest_reg_building(void);
extern void get_new_province_options(void);
extern void get_new_sslot(char *fname);
extern void get_new_tribute(void);
extern int get_next_temp_cohort(int strict);
extern void get_next_viewed_cohort(int direction);
extern int get_next_word_length(char *src, unsigned char *font);
extern void get_no_ov_image(void);
extern int get_number_from_text(char *text);
extern int get_old_mood(void);
extern void get_over_army(void);
extern void get_over_coords(void);
extern void get_pm_from_actual(int actual);
extern int get_pm_over_diamond(int force_zero_offset);
extern int get_pop_level(void);
extern void get_pop_tax_estimate(void);
extern void get_population_and_industry_count(int radius, int mode);
extern void get_population_growth_factor(void);
extern void get_pseudo_map(int direction);
extern unsigned char *get_ptr_to_corner(unsigned char *base_ptr, int size);
extern int get_pumping_memory(void);
extern void get_queried_person(void);
extern void get_query_info(void);
extern int get_rand_max(int max);
extern void get_random_start_points_from_dirc(int dirc, int size, int mask);
extern int get_range1(unsigned char *start, int range, char mask);
extern int get_range3(unsigned char *start, int range, char mask);
extern int get_reg_buildings_in_radius(int x, int y, int span, int radius, unsigned char building_kind);
extern int get_reg_geog_ov_image(void);
extern int get_reg_industries_in_radius(int x, int y);
extern void get_reg_road_elastic(void);
extern void get_reg_wall_elastic(void);
extern int get_region_2x2_start(int cm_ptr);
extern int get_region_invasion_points(int dirc, int from_sea);
extern void get_region_over(void);
extern void get_region_query_info(void);
extern int get_region_revolt_points(void);
extern int get_regroad_start_node(int x, int y);
extern int get_regroad_web(int x, int y);
extern void get_rioter_image(int img);
extern void get_road_cover(void);
extern void get_road_elastic(void);
extern void get_security_ov_image(void);
extern void get_selection_goods_list(int mode);
extern int get_shortest_distance(int x1, int y1, int x2, int y2);
extern void get_start_points(int idx);
extern int get_string_width(char *src, unsigned char *font);
extern unsigned char get_tb_value(int dir);
extern void get_temple_tip(int param_1);
extern void get_text_pointer(int idx, int word_count);
extern int get_tracking_army_distance(int n, int x, int y);
extern void get_units_status(void);
extern void get_unrest_ov_image(void);
extern void get_video_technique(void);
extern void get_villagers(int x_count);
extern void get_wall_cover(void);
extern void get_wall_elastic(void);
extern void get_water_cover(void);
extern void get_water_ov_image(void);
extern int get_web_aqua_dircs(void);
extern int get_web_regroad_dircs(void);
extern int get_wf_dirc(int mode);
extern int get_x_spacing(int p1, int p2, int p3);
extern int get_y_spacing(int p1, int p2, int p3, int p4);
extern void gift_game_loop(int gift_index);
extern void gloop_end(void);
extern void gloop_start(void);
extern void go_16m_palette(char *p);
extern void go_64k_palette(char *p);
extern int goto_army_attack(void);
extern void goto_flag_marker_mode(void);
extern void grey_a_screen(void);
extern void grey_city_map_parts(void);
extern void grey_region_map_parts(void);
extern void handle_collision(int other_idx);
extern void help_game_loop(void);
extern void helping(int msg_id);
extern void high_beep(void);
extern void history_graphs(void);
extern void history_selection(void);
extern int horde_trouble(void);
extern void hospital_coverage(void);
extern void i01_tax_man(void);
extern void i02_market_man(void);
extern void i03_barbarian_man(void);
extern void i04_centurian_man(void);
extern void i05_vigile_man(void);
extern void i06_business_man(void);
extern void i07_rioter_man(void);
extern void in_format_buffer(char *src, int max_char, int line_len, int limit);
extern void inc_elastic_by2(int x, int y, int sptr);
extern void init_battle_ambients(void);
extern void init_battle_gfx_buffers(void);
extern void init_bd(int x1, int y1, int x2, int y2);
extern void init_census(void);
extern void init_choices(struct choice_rec *arr, int count);
extern void init_city_ambients(void);
extern void init_flag_markers(void);
extern void init_help_history(void);
extern void init_legion(void);
extern void init_map_gfx_buffers(void);
extern void init_messages(void);
extern int init_mouse(void);
extern void init_prov_ambients(void);
extern void init_queery_panel(void);
extern void init_region_trouble(void);
extern int init_sample_buffer(int n);
extern void init_slaves(void);
extern void init_ss_entires(void);
extern void init_traders(void);
extern void init_tribute(void);
extern int init_tune_buffer(void);
extern void init_web(void);
extern void initiate_evolution(void);
extern void initreg_game_loop(void);
extern void install_mouse(void);
extern void instant_reform(int unit_no, int formation);
extern void invert_gmn(void);
extern int is_file_on_harddrive(char *fname);
extern int is_fire_covered(int ref);
extern int is_icon_over(int idx);
extern int jump_to_citymap_ptr(int target_ptr);
extern int jump_to_regionmap_ptr(int target_ptr);
extern void just_idle_game_loop(void);
extern int known_world(int prov);
extern void launch_help(int page);
extern void launch_traders(void);
extern void lead_in_logos(void);
extern void library_coverage(void);
extern int link_to_smacker(void);
extern void *load_a_battle_gfx_file(int n, int idx, int aux);
extern void load_a_game(void);
extern int load_battle_graphics(int n);
extern void load_ferret_run(int x, int y, int max_len);
extern void load_format_buffer_from_disk(char *fname, int idx);
extern void load_from_text_buffer(char *dst, int idx, int n, int copy_len);
extern void load_inf(void);
extern int load_map_graphics(int mode, int level);
extern void load_media_entry(void);
extern int load_overlay_graphics(int param);
extern void load_region_map(int province);
extern int load_start_graphics(void);
extern void load_to_temp_palette(char *fname);
extern void load_to_text_buffer(char *src, int idx, int n, int copy_len);
extern int loadgame(char *fname);
extern int loadmodel(char *fname);
extern int lock_region(unsigned int addr, unsigned int size);
extern void loose_arrow_move(void);
extern void lose_game_screen(void);
extern void low_beep(void);
extern void main(int argc, char *argv[]);
extern void main_game_loop(void);
extern void main_path(void);
extern void make_emperor(void);
extern void market_image(void);
extern void media_text_place(int x, int y, int width, int line_count, int alt_x, int alt_width, unsigned char *font);
extern void message(int msg, int is_emperor, int param);
extern void mid2_line_no_sides_base(void);
extern void mid2_line_no_sides_top(void);
extern void mid2_line_with_sides_base(void);
extern void mid2_line_with_sides_top(void);
extern void mid3_line_no_sides_base(void);
extern void mid3_line_no_sides_top(void);
extern void mid3_line_with_sides_base(void);
extern void mid3_line_with_sides_top(void);
extern void mid_line_no_sides_base(void);
extern void mid_line_no_sides_top(void);
extern void mid_line_with_sides_base(void);
extern void mid_line_with_sides_top(void);
extern void mid_slider_var(struct slider_rec *s, int pos);
extern void mloop_end(void);
extern void monthly_update(void);
extern void __cdecl mood_modfication(int seq);
extern void mosaic_frame_divider(int x, int y, int w, int unused);
extern void mouse_follow_cohort(void);
extern void mouse_hunt_enemies(void);
extern int mouse_in_area(int x, int y, int w, int h);
extern int mouse_recorder(void);
extern void mouserange(int xmin, int ymin, int xmax, int ymax);
extern void move_anti_ferret(signed char dir, char mode);
extern void move_army(void);
extern void move_arrow_horiz(void);
extern void move_arrow_vert(void);
extern void move_citizen(void);
extern void move_clock_ferret(signed char dir, char mode);
extern void move_figure(int fig);
extern void move_to_tb_value(int dir);
extern int my_strcmp(char *s1, char *s2, int n);
extern void my_strcpy(char *src, char *dst, int n);
extern int nearest_formation_enemy(void);
extern void neg_sound(void);
extern int new_army_route_point(void);
extern void new_name_game_loop(void);
extern void new_province(void);
extern int next_city_flag(void);
extern int next_danger_flag(void);
extern int next_prov_flag(void);
extern void no_high_beeps(int n);
extern void no_low_beeps(int n);
extern int not_pertinant_statistic1(int p1);
extern int not_pertinant_statistic2(void);
extern int one_aquaduct_ramification(void);
extern int one_letter(unsigned char *font, unsigned char letter);
extern int one_reg_wall_ramification(void);
extern int one_wall_ramification(void);
extern void out_format_buffer(char *out);
extern int out_of_sync(void);
extern int over_forum_menu(void);
extern int over_item(struct menu_item_rec *items, int count, int x_start, int y_base);
extern int over_menu(struct menu_rec *menu, int count);
extern int over_selection(int n, int x, int base_y);
extern void pad_house_with_domus(int prev);
extern void page1_read(void);
extern int pause_db(void);
extern void pay_salary(void);
extern int perform_battle_strip_action(void);
extern int perform_city_strip_action(void);
extern int perform_cohort_box_action(void);
extern int perform_region_strip_action(void);
extern void place2_a_building_base(int style);
extern void place2_a_building_roof(int style);
extern void place2_a_building_top(int style);
extern void place2_sprite(int style);
extern void place3_sprite(int style);
extern void place_3_legend_blocks(int p1, int p2, int p3, int p4);
extern void place_3x_legend_blocks(int p1, int p2, int p3, int p4);
extern void place_9_legend_blocks(void);
extern void place_a_building_base(int style);
extern void place_a_building_roof(int mode);
extern void place_a_building_top(int style);
extern void place_diamond(int style);
extern void place_lefthalf_diamond(void);
extern void place_lefthalf_overlay(int style);
extern void place_legend_block(int sprite_idx, int x, int y);
extern void place_overlay(int style);
extern void place_righthalf_diamond(void);
extern void place_righthalf_overlay(int style);
extern void place_sprite(int side);
extern void plague_an_atom(int sptr);
extern void plague_it(int sptr);
extern void plague_sized(int sptr, int size);
extern void play_ambient_fx(void);
extern void play_speech(int param_1);
extern void play_tune(char *fname, int loops);
extern void plaza_an_area(int x1, int y1, int x2, int y2);
extern void pm_limits(void);
extern void pos_sound(void);
extern void position_mouse(short x, short y);
extern void prebuild_city_item(void);
extern void prebuild_region_item(void);
extern void predict_army_totals(void);
extern void print2_test_info(void);
extern void print3_test_info(void);
extern void print_test_info(void);
extern void print_vesa_info(void);
extern void promotion_game_loop(void);
extern void pull_string_left(char *p, char *end);
extern void pulse_red(int idx, int delta);
extern int pump(unsigned char *src, unsigned char *dst, int length);
extern void push_forward_help_history(void);
extern void push_node_value(char mask);
extern void push_nodes_values(char mask, int flag);
extern void push_shell(int rows);
extern void push_string_right(char *start, char *end);
extern void put_a_font_string(char *str, int x, int y, unsigned char *font, int color);
extern void put_a_hut(int x, int y, int kind);
extern void put_a_media_string(char *text, int x, int y);
extern int put_city_flag(int val);
extern int put_danger_flag(int val);
extern void put_filename_extension(char *fname);
extern void put_message(int msg, int param, int tune);
extern void put_new_node(void);
extern int put_out_a(char type, char x, char y, int unused, char start_idx, char mask, char is_barb);
extern int put_prov_flag(int val);
extern int put_reg_x1_area(int x, int y, unsigned char base_kind, int edge_bits, int color, int strict_flags);
extern int put_reg_x2_area(int x, int y, unsigned char base_kind, int edge_bits, int color, int strict_flags);
extern int put_rm_area(int x, int y, int size, unsigned char base_kind, int edge_bits, int color, int flags);
extern int put_x1_area(int x, int y, char base_kind, int edge_bits, int color);
extern int put_x2_area(int x, int y, char base_kind, int edge_bits, int color);
extern int put_x3_area(int x, int y, char base_kind, int edge_bits, int color);
extern int put_x4_area(int x, int y, char base_kind, int edge_bits, int color);
extern int putting_out_fire(void);
extern void queery_game_loop(void);
extern void __pascal radfree(void *ptr);
extern void *__pascal radmalloc(unsigned int size);
extern int raider_in_region(int dirc, int from_sea);
extern int raider_trouble(void);
extern void raise_all_units_morale(int skip_type, int delta_a, int delta_b);
extern void random(void);
extern void random_event(void);
extern void random_target(void);
extern char read_config(char *fname, char *buf);
extern void read_installed_mouse(void);
extern void read_mouse(void);
extern int readfile(const char *fname, void *buf, int size, int offset);
extern void rebuild_figures_image_data(void);
extern void recognise_card(void);
extern void reconst(void);
extern void redraw_icon_bits(void);
extern void reduce_villa_to_domus(unsigned char *cm);
extern void reform(int unit_ref, int mode, int force);
extern void refresh_a_bigger_square(int x, int y);
extern void refresh_a_square(int x, int y, char val);
extern void refresh_battle_zoom_mode(int level);
extern void refresh_big_action_square(int x, int y);
extern void refresh_figure2_square(int x, int y);
extern void refresh_figure3_square(int x, int y);
extern void refresh_figure_square(int x, int y);
extern void refresh_region_sprite_square(int x, int y);
extern void refresh_sprite2w_square(int x, int y);
extern void refresh_sprite_square(int x, int y);
extern void refresh_svga_screen(void);
extern void refresh_zoom_mode(int level);
extern int reg_industry_quote(int x);
extern int reg_port_quote(int base);
extern int reg_road_ramifications(int x, int y);
extern int reg_tpost_quote(int base);
extern int reg_wall_ramifications(int x, int y);
extern void region_census(void);
extern int region_go_to_target(int kind);
extern int region_icon_allowed(int idx);
extern void region_map_screen(int do_black_out);
extern void region_trouble(void);
extern void remove_army(int n);
extern void remove_citizen(int n);
extern void remove_envoy(void);
extern void remove_figure(int n);
extern void remove_house(void);
extern void remove_unit(int n);
extern void request_outcome(void);
extern void reshow_initreg_box(void);
extern void restore_city_from_undo_buffer(void);
extern void restore_picture_part(unsigned char *sprite_addr, int sprite_idx);
extern void restore_region_from_undo_buffer(void);
extern int revolt_in_region(int dirc, int from_sea);
extern int revolt_trouble(void);
extern void rewind_help_history(void);
extern int road_ramifications(int x, int y);
extern void road_trouble(void);
extern void rotate_pm_anticlockwise(void);
extern void rotate_pm_clockwise(void);
extern int run_2_map_ferrets(int param1, unsigned char *map_base, int map_wi, int map_hi, int cell_size, int start_x, int start_y, int targ_x, int targ_y);
extern void run_anti_ferret(void);
extern void run_clock_ferret(void);
extern int run_to_new_aqua_node(void);
extern int run_to_new_regroad_node(void);
extern int running_delay1(void);
extern void running_ind_tax(void);
extern void running_pop_tax(void);
extern void s01_wait(void);
extern void s02_death(void);
extern void s03_map_admin(void);
extern void s04_map_markets(void);
extern void s05_maraude_to_top_spot(void);
extern void s06_quell_trouble(void);
extern void s07_army_patrol(void);
extern void s08_vigile_patrol(void);
extern void s09_fire_fight(void);
extern void s10_get_business(void);
extern void s11_riot(void);
extern void s12_goto_riot(void);
extern void sa01_wait(void);
extern void sa02_death(void);
extern void sa03_army_move(void);
extern void sa04_army_attack(void);
extern void sa05_army_return(void);
extern void sa06_army_land_raid(void);
extern void sa07_army_land_invade(void);
extern void sa08_army_stuck(void);
extern void sa09_army_siege(void);
extern void sa10_army_demobed(void);
extern void sa11_army_sail_to_port(void);
extern void sa12_army_sail_home(void);
extern void sa13_army_sail_round_coast(void);
extern void sa14_army_sail_to_shore(void);
extern void sa15_sink(void);
extern void sa16_army_lurk_round_coast(void);
extern int sail_to_target(int kind);
extern void samples_game_loop(void);
extern void save_a_game(void);
extern void save_format_buffer_to_disk(char *fname, int idx);
extern void save_history(void);
extern void save_inf(void);
extern void save_undo_info(void);
extern int savegame(char *fname);
extern void scatter(void);
extern void scroll(void);
extern int scroll_speed(void);
extern void select_a_unit(int fig_idx, int mode);
extern void select_all_figures(void);
extern void select_drag_figures(void);
extern int select_filename(int mode);
extern void serve_sample(int sample_handle, unsigned char **buf, int size);
extern void set_2_neighbours_if_not_aquaductorresevoir(int x, int y, int sptr, unsigned char field_off, unsigned char value, int north_south);
extern void set_2_neighbours_if_not_wallortower(int x, int y, int sptr, unsigned char field_off, unsigned char value, int north_south);
extern void set_4_neighbours(int x, int y, int sptr, unsigned char field_off, unsigned char value);
extern void set_4_neighbours_if_not_aquaductorresevoir(int x, int y, int sptr, unsigned char field_off, unsigned char value);
extern void set_4_neighbours_if_not_wallortower(int x, int y, int sptr, unsigned char field_off, unsigned char value);
extern void set_4_rm_neighbours_if_not_aquaductorresevoir(int x, int y, int sptr, unsigned char field_off, unsigned char value);
extern void set_4_rm_neighbours_if_not_wallortower(int x, int y, int sptr, unsigned char field_off, unsigned char value);
extern void set_ai_flank_move(int mode);
extern void set_ai_unit_auto_fire(void);
extern void set_ai_unit_beserk(void);
extern void set_ai_unit_delayed_beserk(void);
extern void set_ai_unit_move(int dx, int dy);
extern void set_ai_unit_withdraw(int dx, int dy);
extern void set_ambient_minimum(int idx, int min);
extern void set_attack_count(int n);
extern void set_battle_death_fx(int unit_type);
extern void set_battle_fight_fx(int event);
extern void set_battle_march_fx(int unit_type);
extern void set_city_ambient(int kind);
extern void set_current_cohort_totals(void);
extern void set_db_sound(char *fname);
extern void set_defense_shield(int n);
extern void set_ew_polar(int x, int y, int sptr, unsigned char field_off, unsigned char value);
extern void set_figure_map_refresh(int a, int b, int c, int d, int e, int f);
extern void set_first_nodes_values(int mask);
extern void set_language(int language);
extern void set_map_ref(int x, int y, int size);
extern void set_missile_fight_fx(int event);
extern void set_missile_fire_fx(int missile_type);
extern void set_missile_fire_range(int n);
extern void set_mode3(void);
extern void set_mouse(void);
extern void set_mouse_limits(void);
extern void set_mouse_refresh(void);
extern void set_new_province(void);
extern void set_ns_polar(int x, int y, int sptr, unsigned char field_off, unsigned char value);
extern void set_palette(char *p);
extern void set_pri_sound(char *fname, int arg2);
extern void set_prov_ambient(int event);
extern void set_range(int x, int y, int range, unsigned char field_off, unsigned char value);
extern void set_rm_range(int x, int y, int half_width, char field_offset, char kind_byte);
extern void set_route_elastic(void);
extern void set_route_elastic_range(int r);
extern void set_samples_volume(void);
extern void set_sequences_volume(void);
extern void set_sound(char *fname, int arg2);
extern int set_svga_640_480(int mode);
extern void set_this_ambient(int idx);
extern void set_unit_to_fight(int start_fig);
extern void set_unit_to_rout(int unit_no);
extern void set_vga_256x(void);
extern void set_vga_mode(int mode);
extern void set_vga_palette(char *p);
extern void set_vga_palette_range(char *p, int start, int end);
extern void setup_battle(void);
extern void setup_battle_screen_refresh(void);
extern void setup_enemy_units(void);
extern void setup_game(void);
extern void setup_history_data(void);
extern void setup_map_screen_long_refresh(int fill);
extern void setup_map_screen_refresh(void);
extern void setup_refresh_area(int x, int y, int w, int h, int value);
extern void setup_roman_units(void);
extern void setup_scratch_buffer(void);
extern void setup_svga_refresh_data(void);
extern void setup_whole_screen_refresh(void);
extern void sf01_wait(void);
extern void sf02_death(void);
extern void sf03_move(void);
extern void sf04_fight(void);
extern void sf06_defend(void);
extern void sf07_reform(void);
extern void sf08_withdraw(void);
extern void sf09_look_for_fight(void);
extern void sf10_hunt_for_fight(void);
extern void sf11_fire_missile(void);
extern void sf12_rout(void);
extern void sf13_autofire_missile(void);
extern void sf14_opertunist_fire(void);
extern void sf15_move_and_reform(void);
extern void show_Xconfirming_panel(int what, int x, int y);
extern void show_a_32_block(int x, int y, int sprite_no);
extern void show_a_mosaic_blank(int x, int y, int cols, int rows);
extern void show_a_mosaic_frame(int x, int y, int w, int h);
extern void show_a_mosaic_window(int x, int y, int w, int h);
extern void show_a_system_blank(int x, int y, int w, int h);
extern void show_a_system_window(int x, int y, int cols, int rows);
extern void show_about_box(void);
extern void show_accounts(void);
extern void show_adjusting_panel(int what, int x, int y, int kind);
extern void show_aim_highlight(void);
extern void show_an_exit_button(int x, int y);
extern void show_basic_message(int msg, int param);
extern void show_battle_intro_screen(void);
extern void show_battle_landfill(int start_row, int row_count, int screen_x, int screen_y);
extern void show_battle_outtro_screen(void);
extern void show_battle_setup_box(void);
extern void show_battlemap(void);
extern void show_battlemap_base(void);
extern void show_battlemap_top(void);
extern void show_buttons(int x, int y, struct button_rec *buttons, int count);
extern void show_census_panel(void);
extern void show_city_landfill(int x_start, int y_start);
extern void show_citymap(void);
extern void show_citymap_base(void);
extern void show_citymap_sprites(void);
extern void show_citymap_top(void);
extern void show_cohort_box(void);
extern void show_cohort_landfill(int army_idx, int x_start, int y_start);
extern void show_confirming_panel(int what, int x, int y);
extern void show_cursor(unsigned char *font);
extern void show_date(int year, int x, int y, int mode);
extern void show_debug_screen(void);
extern void show_detailed_query_panel(void);
extern void show_diamond_ptr(void);
extern void show_directory(int scroll_top);
extern void show_donation_box(void);
extern void show_donation_level(void);
extern void show_emperor_message(int msg, int is_emperor);
extern void show_empire_bottom_slab(void);
extern void show_empire_top_slab(void);
extern void show_estimate(void);
extern void show_exit_box(void);
extern void show_final_bribe_box(void);
extern void show_first_region_box(void);
extern void show_forum_screen(void);
extern void show_fx_box(int p1);
extern void show_general_query_panel(void);
extern void show_gift_amount(int gift_index);
extern void show_gift_box(void);
extern void show_help_page(void);
extern int show_history_graph(int x, int y, int idx);
extern void show_icon_strip(void);
extern void show_icons(struct icon_rec *icons, int count);
extern void show_initreg_box(void);
extern void show_landfill(int p1, int p2);
extern void show_latest_route(void);
extern void show_lbm(const char *fname);
extern int show_left_overlay(int style);
extern void show_loadsave_box(int title_id);
extern void show_menu_items(struct menu_item_rec *items, int x, int y, int text_group, int count, int active);
extern void show_menus(struct menu_rec *menus, int count, int active);
extern void show_mercs(void);
extern void show_messages(void);
extern void show_mouse(int id);
extern int show_move_highlight(void);
extern void show_name_choice(void);
extern void show_new_name_box(void);
extern void show_no_provinces_box(void);
extern void show_non_cohort_box(void);
extern void show_one_ptr(int x, int y);
extern void show_ov_bar(void);
extern void show_ov_legend_panel(void);
extern int show_overlay(int style);
extern void show_paused(void);
extern void show_peace_level(void);
extern void show_people_query_panel(void);
extern void show_personal_cash_stats(void);
extern void show_picfile(char *fname);
extern void show_pl8file(const char *fname, int rows);
extern void show_please_wait(void);
extern void show_query_business_advice(void);
extern void show_query_house_advice(void);
extern void show_query_panel(void);
extern void show_query_panel_heading(int y);
extern void show_querymode_panel(void);
extern void show_recruitment(void);
extern void show_region_landfill(int x_start, int y_start);
extern void show_region_query_panel(int y);
extern void show_regionmap(void);
extern void show_regionmap_base(void);
extern void show_regionmap_top(void);
extern void show_regions_in_empire(void);
extern void show_regions_on_offer(void);
extern void show_request_amount(void);
extern int show_right_overlay(int style);
extern void show_selection_box(int p1, int x, int y, int p4);
extern void show_selections(struct selection_rec *list, int count, int x, int y, int what, int selected);
extern void show_skill1_box(void);
extern void show_skill2_box(void);
extern void show_skill_level(void);
extern void show_slave_allocation(void);
extern void show_slave_welfare_bill(void);
extern void show_tax_rates(void);
extern void show_temple_tip(void);
extern void show_this_tribune(void);
extern void show_top_line(void);
extern void show_tribunes_report(int army_idx, int x, int y, int mode);
extern void show_turbo_panel(void);
extern void show_tutorial_timer(void);
extern void show_want_promotion_box(int rank);
extern void show_warning_panel(int what, int x, int y);
extern void show_year_end_screen(void);
extern char sim_mouse(void);
extern void skill1_game_loop(void);
extern void skill2_game_loop(void);
extern void slave_costs(void);
extern void slave_estimate(void);
extern void slave_welfare(void);
extern int slider_control(struct slider_rec *sliders, int count);
extern void smooth_ferret_run(int margin, unsigned char *map_base, int map_wi, int map_hi, int cell_size, int x1, int y1, int x2, int y2);
extern void sooth_mood(void);
extern void spread_fire_and_plague_and_unrest(int rows);
extern void spread_fire_atom(int sptr, int dir);
extern void spread_plague_atom(int sptr, int dir);
extern void sprites_no_sides(void);
extern void sprites_with_sides(void);
extern void start_a_new_game(void);
extern void start_a_promotion(void);
extern void start_aim(void);
extern void start_game(void);
extern void start_move(void);
extern char *start_samples(void);
extern char *start_sequences(void);
extern void start_smacking(char *p, int left, int top, int mode);
extern char *start_sound(char *buf, int loop_count);
extern void start_sounds(void);
extern int start_system(void);
extern char *start_tune(unsigned char *seq_arg, int sequence_num, int slot);
extern void stop_all_sounds(void);
extern void stop_db(void);
extern void stop_samples(void);
extern void stop_sequences(void);
extern void stop_smacking(void);
extern void stop_sounds(void);
extern void stop_system(void);
extern void stop_tune(void);
extern void stop_tune0(void);
extern int stretch_house(int n, int variant);
extern int stretch_to_2x2_house(int p1, int unused, int orient);
extern int stretch_to_3x3_house(int p1, int unused, int orient);
extern void string_to_upper(char *s);
extern void strip_fb_spaces(void);
extern void strip_leading_space(signed char *s);
extern void strip_spaces(char *s);
extern void strip_trailing_space(signed char *s);
extern int swap_2_figures(void);
extern void swap_background_to(int idx);
extern void swap_background_to_red(void);
extern void swap_circus_gfx(void);
extern void swap_screens(void);
extern void take_census(int rows);
extern void take_from_warehouses(int amount, int goods);
extern void target_from_army_dirc(int dir);
extern void target_from_dirc(int dir);
extern void target_from_figure_dirc(int dir);
extern int test_area_for_population(int extra, int x, int y, int radius);
extern void test_beeps(void);
extern int test_cd_drive(void);
extern void test_citymap_neighbours_negedge(char mask);
extern void test_citymap_neighbours_posedge(char mask);
extern void test_elastic_range(int r, unsigned char reject_mask);
extern int test_fire_zones(void);
extern int test_for_any_admin(int cm_ptr, int n);
extern int test_for_army_attack(void);
extern void test_for_delimiter(void);
extern int test_for_ew_polar_walls(int x, int _edx_unused, int sptr);
extern int test_for_next_to_region_wall(int x, int y);
extern int test_for_ns_polar_walls(int _eax_unused, int y, int sptr);
extern int test_for_same_fig_to(int dirc);
extern void test_inf_settings(void);
extern int test_next_to_river(void);
extern int test_perimeter_for_road_and_forum(int x, int y, int size, int road_only);
extern void test_range_for(int x, int y, int radius, int mode);
extern int test_range_for_road(int x, int y, int radius);
extern int test_reform_pattern(int unit_ref, int dir);
extern void test_regionmap_neighbours_negedge(char mask);
extern void test_regionmap_neighbours_posedge(char mask);
extern void test_rm_elastic_range(int strict, int r, unsigned char reject_mask);
extern void test_type_citymap_neighbours_negedge(unsigned char type);
extern void test_type_citymap_neighbours_posedge(unsigned char type);
extern void test_type_regionmap_neighbours_negedge(unsigned char type);
extern void test_type_regionmap_neighbours_posedge(unsigned char type);
extern int test_zone_for_closest_fire(void);
extern void this_region(void);
extern void this_region_box(int p1);
extern void three_by_three(int x, int y);
extern int timer(int mode);
extern void to_fb(void);
extern char to_upper(char c);
extern void tog_anims_game_loop(void);
extern void tog_yearend_game_loop(void);
extern int toggle_city_flag(int val);
extern int toggle_prov_flag(int val);
extern void top_it(int side);
extern int totalXpercent(int a, int b);
extern int totalXpercentX100(int a, int b);
extern int trace_back_ferret(void);
extern void trace_back_route_elastic(void);
extern int trace_forward_ferret(int steps);
extern void train_soldiers(void);
extern void transform_aquaduct_elastic(int r);
extern int transform_reg_road_elastic(int r);
extern void transform_reg_wall_elastic(int r);
extern void transform_road_elastic(int r);
extern void transform_wall_elastic(int r);
extern int try_a_battlemap_square(int dir);
extern int try_a_citymap_square(int dir, int kind, int unused);
extern int try_a_regionmap_square(int dir, int kind, int third);
extern int try_a_seamap_square(int dir, int kind, int third);
extern int try_this_battlemap_square(int cell_off);
extern int try_this_citymap_square(int cm_ptr, int kind);
extern int try_this_regionmap_square(int target, int kind, int third);
extern int try_this_seamap_square(int cell_off, int kind, int third);
extern void tune_game_loop(void);
extern void tutorial_test_for_forum_access(void);
extern void tutorial_test_for_water_distribution(void);
extern void unflag_all_cm(char field_off, int mask);
extern void unflag_all_rm(char field_off, int mask);
extern void unflag_all_rm_xwarehouse(void);
extern void unflag_rm_area(int x, int y, int size, char mask_byte);
extern void unset_vga_256x(void);
extern void up_slider_var(struct slider_rec *s);
extern void update(short c);
extern void update_battle_landfill(void);
extern void update_time(void);
extern void update_tribune_flag(int mode);
extern void update_units_ai(void);
extern void update_units_morale(void);
extern int use_city_overmap_to_move(void);
extern int use_region_overmap_to_move(void);
extern int valueDIVtotal(int value, int total);
extern void vhigh_beep(void);
extern void wait_click(void);
extern void wait_key(void);
extern int wall_ramifications(int x, int y);
extern void wall_trouble(void);
extern int want_promotion(int level);
extern void war_trouble(void);
extern void water_trouble(void);
extern void we_retreat(void);
extern void we_surrender(void);
extern void write_clipped_image(unsigned char *buf, int id, int x, int y, int clip_x_lo, int clip_x_hi, int clip_y_lo, int clip_y_hi);
extern void write_general_sprite(int idx, int x, int y);
extern void write_general_sprite_with_front_ofset(int idx, int x, int y, int front_offset);
extern void write_image(unsigned char *buf, int id, int x, int y);
extern int write_to_file(char *fname, char *buf, int size, int offset);
extern int writefile(const char *fname, char *buf, int size);
extern void wvbl2(void);
extern void xclip(int clip_left, int clip_right);
extern void xor_a_diamond_lhs_top(int x, int y, int width, int height, int color);
extern void xor_a_diamond_rhs_top(int x, int y, int width, int height, int color);
extern void xor_a_diamond_top(int x, int y, int width, int height, int colour);
extern void yclip(int clip_top, int clip_bottom);
extern void year_end_accounts(void);
extern void year_end_game_loop(void);
extern void yearly_update(void);

/* Excluded from c2_funcs.h to preserve PS.EXE's implicit-int call
 * shape (Rule 37 reverse case) — these functions are declared
 * with a narrower-than-int return in their defining TU but PS
 * call sites emit 'test eax, eax' because the original source
 * had no prototype visible.  See _IMPLICIT_INT_FUNCTIONS in
 * c2/commands/c_source.py.
 *
 * click_handler, colour_cycle_delay1, colour_cycle_delay2, get_heading
 */

/* ── Asm-module primitives (library.asm, sprites.asm, dia_*.asm) ─ */
/* Canonical signatures auto-derived from per-file extern decls.   */
/* Conflicting forms are resolved by picking the most-typed variant.*/

extern void copy(unsigned char *src, unsigned char *dst, int n);
extern int depress(unsigned char *dst, unsigned char *src);
extern void place_24x24_block(unsigned char *panel_addr);
extern void place_2x2_block(unsigned char *src, int screen_off);
extern void place_4x4_block(unsigned char *src, int screen_off);
extern void place_6x6_block(unsigned char *src, int screen_off);
extern void place_8x8_block(unsigned char *src, int screen_off);
extern void place_i_sprite(unsigned char *sprite_addr);
extern void refresh_16x16_partblock(int screen_off, unsigned short bank_off, int width);
extern void write_i_font(unsigned char *font);
extern void write_i_left_font(unsigned char *font);
extern void write_i_right_font(unsigned char *font);

#endif /* C2_FUNCS_H */
