"""The save format's generated accessors must match the schema, and the
bundled FlatBuffers runtime must stay the drop-in subset it was taken as."""

import filecmp
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "src/platform/common/c2_save.fbs"
GENERATED = ROOT / "src/platform/common/c2_save_gen"
RUNTIME = ROOT / "third_party/flatcc"


def test_generated_accessors_are_checked_in():
    for name in ("c2_save_reader.h", "c2_save_builder.h", "c2_save_verifier.h",
                 "flatbuffers_common_reader.h", "flatbuffers_common_builder.h"):
        assert (GENERATED / name).is_file(), name


def pinned_version():
    """The version the checked-in accessors were generated with."""
    header = (GENERATED / "c2_save_reader.h").read_text()
    match = re.search(r"Generated by flatcc (\d+\.\d+\.\d+)", header)
    assert match, "generated header carries no flatcc version"
    return match.group(1)


def test_bundled_runtime_is_the_pinned_version():
    # flatcc_version.h is not bundled (it is the compiler's); the runtime
    # headers carry the version in their generated-code contract instead.
    builder = (RUNTIME / "include/flatcc/flatcc_builder.h").read_text()
    assert "flatcc_builder_finalize_aligned_buffer" in builder
    readme = (ROOT / "third_party/README.md").read_text()
    assert f"| `flatcc/` | https://github.com/dvidelabs/flatcc | {pinned_version()}" in readme, (
        "third_party/README.md must record the same flatcc version the accessors were generated with")
    flake = (ROOT / "flake.nix").read_text()
    assert f'version = "{pinned_version()}";' in flake, (
        "flake.nix must pin the same flatcc version the accessors were generated with")


def test_generated_accessors_match_the_schema():
    flatcc = shutil.which("flatcc")
    if flatcc is None:
        pytest.skip("flatcc not on PATH; run tools/regen-save-schema.sh in the dev shell")
    found = subprocess.run([flatcc, "--version"], capture_output=True, text=True, check=True).stdout
    version = re.search(r"version:\s*(\d+\.\d+\.\d+)", found)
    if version is None or version.group(1) != pinned_version():
        pytest.skip(f"PATH has flatcc {version.group(1) if version else '?'}, accessors were generated with "
                    f"{pinned_version()}; use the dev shell's")
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run([flatcc, "-a", "-o", tmp, str(SCHEMA)], check=True)
        for path in sorted(Path(tmp).glob("*.h")):
            checked_in = GENERATED / path.name
            assert checked_in.is_file(), f"{path.name} missing from {GENERATED}"
            assert filecmp.cmp(path, checked_in, shallow=False), (
                f"{path.name} is stale; run tools/regen-save-schema.sh")


def test_schema_states_its_contract():
    text = SCHEMA.read_text()
    assert 'file_identifier "C2SV"' in text
    assert "root_type Save" in text
    assert "format_version:uint = 1" in text
    # No pointers, no derived state: the two engine records the format
    # reasons about name their fields; occupancy and ring indices are absent.
    assert "struct CityCell" in text and "struct Citizen" in text
    assert "citizen_a" not in text.split("struct CityCell")[1].split("}")[0]
    assert "history_end_ptr" not in text
    assert "envoy:ushort" in text and "target:ushort" in text


def test_bundled_flatcc_runtime_is_the_runtime_only():
    sources = sorted(p.name for p in (RUNTIME / "src/runtime").glob("*.c"))
    assert sources == ["builder.c", "emitter.c", "refmap.c", "verifier.c"]
    headers = {p.name for p in (RUNTIME / "include/flatcc").glob("*.h")}
    assert "flatcc_json_parser.h" not in headers
    assert "flatcc.h" not in headers, "the compiler API does not belong in the runtime"
    assert (RUNTIME / "LICENSE").is_file() and (RUNTIME / "NOTICE").is_file()
