"""Hash command: compute SHA256 hashes for CD extraction directories."""

from __future__ import annotations

import hashlib
import os
from pathlib import Path
from typing import Annotated, Optional

import typer


def _compute_sha256(file_path: Path) -> str:
    sha256 = hashlib.sha256()
    try:
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(4096), b""):
                sha256.update(chunk)
        return sha256.hexdigest()
    except OSError as e:
        typer.echo(f"Error reading {file_path}: {e}", err=True)
        return ""


def _get_all_files(directory: Path) -> list[Path]:
    files: list[Path] = []
    for root, dirs, filenames in os.walk(directory):
        dirs.sort()
        filenames.sort()
        for filename in filenames:
            p = Path(root) / filename
            if p.is_file():
                files.append(p)
    return files


def _hashes_file_path(directory: Path) -> Path:
    """Determine where to write the .sha256 file.

    For CDs/extracted/<name>/ → write to data/hashes/<name>.sha256.
    Otherwise → write to data/hashes/<name>.sha256 relative to cwd.
    """
    return Path("data/hashes") / f"{directory.name}.sha256"


def _process_directory(directory: Path, force: bool) -> None:
    hashes_file = _hashes_file_path(directory)

    if hashes_file.exists() and not force:
        typer.echo(f"Warning: overwriting existing hashes file: {hashes_file}")

    if not directory.exists() or not directory.is_dir():
        typer.echo(f"Error: not a directory: {directory}", err=True)
    typer.echo(f"Computing hashes for: {directory}")
    files = _get_all_files(directory)
    hashes: dict[str, str] = {}

    for file_path in files:
        rel = file_path.relative_to(directory)
        typer.echo(f"  Hashing: {rel}")
        h = _compute_sha256(file_path)
        if h:
            hashes[str(rel).replace(os.sep, "/")] = h

    typer.echo(f"  Computed {len(hashes)} file hashes")

    if not hashes:
        typer.echo(f"No files found in: {directory}")
        return

    hashes_file.parent.mkdir(parents=True, exist_ok=True)
    with open(hashes_file, "w", encoding="utf-8") as f:
        f.write(f"# SHA256 hashes for directory: {directory.name}\n")
        f.write("# Generated by c2 cd hash\n")
        f.write("# Format: <hash>  <relative_path>\n\n")
        for path in sorted(hashes):
            f.write(f"{hashes[path]}  {path}\n")

    typer.echo(f"Saved hashes to: {hashes_file}")


def hash_cmd(
    directories: Annotated[
        Optional[list[Path]],
        typer.Argument(help="Directories to hash (auto-discovers CDs/extracted/ if omitted)"),
    ] = None,
) -> None:
    """Compute SHA256 hashes for CD extraction directories."""
    dirs_to_process: list[Path] = list(directories or [])

    if not dirs_to_process:
        # Auto-discover CDs/extracted/
        extracted = Path("CDs/extracted")
        if extracted.exists():
            typer.echo("Auto-discovering in CDs/extracted/...")
            for item in sorted(extracted.iterdir()):
                if item.is_dir():
                    dirs_to_process.append(item)
                    typer.echo(f"  Found: {item}")

    if not dirs_to_process:
        typer.echo("No directories to process. Specify directories or run from repo root.")
        raise typer.Exit(1)

    typer.echo(f"Processing {len(dirs_to_process)} directories...")
    for directory in dirs_to_process:
        typer.echo(f"\n{'=' * 60}")
        _process_directory(directory, force=False)

    typer.echo(f"\n{'=' * 60}")
    typer.echo("Hash computation complete!")
