#ifndef C2_PORT_TEXT_H
#define C2_PORT_TEXT_H

#include <stddef.h>

/*
 * Compiled-in game text. Every language's gettext file (po/ *.po, with
 * po/c2.pot as English) is embedded in the executable; at startup the
 * selected one is parsed and rebuilt into the recovered engine's own
 * Textfile (C2.ENG) and Helpfile (HELP.ENG) layouts, which readfile()
 * then serves instead of the files on the disc. The engine addresses
 * text exactly as before; nothing in recovered source changes.
 */

struct c2_port_language {
    const char *tag;    /* "de" */
    const char *name;   /* "Deutsch", from the po header X-C2-Name */
    const char *detect; /* a string unique to that language's C2.ENG */
};

/* The bundled languages, in build order (English first). */
int c2_port_text_language_count(void);
const struct c2_port_language *c2_port_text_language(int index);

/* Explicit choice (--language, launcher). Unknown tags are rejected;
 * NULL drops the choice so detection decides again. */
int c2_port_text_select(const char *tag);
/* The tag in effect: the explicit choice, else the one detected from the
 * game data's C2.ENG, else "en". Detection happens on first use. */
const char *c2_port_text_selected(void);
/* Tag whose detect string matches this C2.ENG, or NULL. */
const char *c2_port_text_detect(const unsigned char *c2eng, size_t size);

/* readfile() hooks: non-zero when the name is the language or help file,
 * in which case *bytes_read is what the engine receives. */
int c2_port_text_is_language_file(const char *filename);
int c2_port_text_is_help_file(const char *filename);
int c2_port_text_read(const char *filename, void *buffer, size_t size,
                      size_t offset, size_t *bytes_read);

/* Whole rebuilt files, for tests and tools. */
const unsigned char *c2_port_text_c2eng(size_t *size);
const unsigned char *c2_port_text_helpeng(size_t *size);
void c2_port_text_shutdown(void);

/* Embedded bundle (generated by cmake/EmbedText.cmake). */
struct c2_text_bundle_entry {
    const char *tag;
    const unsigned char *data;
    size_t size;
};
extern const struct c2_text_bundle_entry c2_text_bundle[];
extern const int c2_text_bundle_count;

#endif /* C2_PORT_TEXT_H */
