#ifndef C2_SAVE_COMPAT_H
#define C2_SAVE_COMPAT_H

#include <stddef.h>

#include "c2_types.h"

#define C2_SAVE_FIGURE_COUNT 201
#define C2_SAVE_FIGURE_SIZE 88
#define C2_SAVE_FIGURES_SIZE (C2_SAVE_FIGURE_COUNT * C2_SAVE_FIGURE_SIZE)

#define C2_SAVE_ARROW_COUNT 201
#define C2_SAVE_ARROW_SIZE 45
#define C2_SAVE_ARROWS_SIZE (C2_SAVE_ARROW_COUNT * C2_SAVE_ARROW_SIZE)

/* The save table is a 500-entry array in the original with no terminator;
 * PORT_FIX_DATA_LAYOUT_READS splits two entries in four (same bytes). */
#if PORT_FIX_DATA_LAYOUT_READS
#  define C2_SAVE_REGISTRY_CAPACITY 502
#else
#  define C2_SAVE_REGISTRY_CAPACITY 500
#endif
#define C2_SAVE_STATE_SIZE 221745
#define C2_SAVE_HISTORY_SIZE 4000
#define C2_SAVE_FILE_SIZE (C2_SAVE_STATE_SIZE + C2_SAVE_HISTORY_SIZE)
#define C2_SAVE_FIGURES_OFFSET 20202
#define C2_SAVE_ARROWS_OFFSET \
    (C2_SAVE_FIGURES_OFFSET + C2_SAVE_FIGURES_SIZE)


#endif /* C2_SAVE_COMPAT_H */
