#ifndef C2_SAVE_READER_H
#define C2_SAVE_READER_H

/* Generated by flatcc 0.6.3 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "C2SV"
#undef flatbuffers_extension
#define flatbuffers_extension "sav"

typedef struct c2_save_CityCell c2_save_CityCell_t;
typedef const c2_save_CityCell_t *c2_save_CityCell_struct_t;
typedef c2_save_CityCell_t *c2_save_CityCell_mutable_struct_t;
typedef const c2_save_CityCell_t *c2_save_CityCell_vec_t;
typedef c2_save_CityCell_t *c2_save_CityCell_mutable_vec_t;
typedef struct c2_save_Citizen c2_save_Citizen_t;
typedef const c2_save_Citizen_t *c2_save_Citizen_struct_t;
typedef c2_save_Citizen_t *c2_save_Citizen_mutable_struct_t;
typedef const c2_save_Citizen_t *c2_save_Citizen_vec_t;
typedef c2_save_Citizen_t *c2_save_Citizen_mutable_vec_t;
typedef struct c2_save_HistorySample c2_save_HistorySample_t;
typedef const c2_save_HistorySample_t *c2_save_HistorySample_struct_t;
typedef c2_save_HistorySample_t *c2_save_HistorySample_mutable_struct_t;
typedef const c2_save_HistorySample_t *c2_save_HistorySample_vec_t;
typedef c2_save_HistorySample_t *c2_save_HistorySample_mutable_vec_t;

typedef const struct c2_save_Save_table *c2_save_Save_table_t;
typedef struct c2_save_Save_table *c2_save_Save_mutable_table_t;
typedef const flatbuffers_uoffset_t *c2_save_Save_vec_t;
typedef flatbuffers_uoffset_t *c2_save_Save_mutable_vec_t;
#ifndef c2_save_CityCell_file_identifier
#define c2_save_CityCell_file_identifier "C2SV"
#endif
/* deprecated, use c2_save_CityCell_file_identifier */
#ifndef c2_save_CityCell_identifier
#define c2_save_CityCell_identifier "C2SV"
#endif
#define c2_save_CityCell_type_hash ((flatbuffers_thash_t)0xa4cd3ca8)
#define c2_save_CityCell_type_identifier "\xa8\x3c\xcd\xa4"
#ifndef c2_save_CityCell_file_extension
#define c2_save_CityCell_file_extension "sav"
#endif
#ifndef c2_save_Citizen_file_identifier
#define c2_save_Citizen_file_identifier "C2SV"
#endif
/* deprecated, use c2_save_Citizen_file_identifier */
#ifndef c2_save_Citizen_identifier
#define c2_save_Citizen_identifier "C2SV"
#endif
#define c2_save_Citizen_type_hash ((flatbuffers_thash_t)0x5dcb459)
#define c2_save_Citizen_type_identifier "\x59\xb4\xdc\x05"
#ifndef c2_save_Citizen_file_extension
#define c2_save_Citizen_file_extension "sav"
#endif
#ifndef c2_save_HistorySample_file_identifier
#define c2_save_HistorySample_file_identifier "C2SV"
#endif
/* deprecated, use c2_save_HistorySample_file_identifier */
#ifndef c2_save_HistorySample_identifier
#define c2_save_HistorySample_identifier "C2SV"
#endif
#define c2_save_HistorySample_type_hash ((flatbuffers_thash_t)0x2bce2567)
#define c2_save_HistorySample_type_identifier "\x67\x25\xce\x2b"
#ifndef c2_save_HistorySample_file_extension
#define c2_save_HistorySample_file_extension "sav"
#endif
#ifndef c2_save_Save_file_identifier
#define c2_save_Save_file_identifier "C2SV"
#endif
/* deprecated, use c2_save_Save_file_identifier */
#ifndef c2_save_Save_identifier
#define c2_save_Save_identifier "C2SV"
#endif
#define c2_save_Save_type_hash ((flatbuffers_thash_t)0x96152c36)
#define c2_save_Save_type_identifier "\x36\x2c\x15\x96"
#ifndef c2_save_Save_file_extension
#define c2_save_Save_file_extension "sav"
#endif


struct c2_save_CityCell {
    alignas(2) uint8_t base_kind;
    alignas(1) uint8_t terrain;
    alignas(1) uint8_t road_aqueduct;
    alignas(1) uint8_t edge_bits;
    alignas(1) uint8_t extra_edge;
    alignas(1) uint8_t activity_a;
    alignas(1) uint8_t activity_b;
    alignas(1) uint8_t building;
    alignas(1) uint8_t range_flag;
    alignas(1) uint8_t fpu_flag;
    alignas(1) uint8_t entertainment;
    alignas(1) uint8_t education;
    alignas(1) uint8_t health;
    alignas(1) uint8_t land_value;
    alignas(1) uint8_t fire;
    alignas(1) uint8_t security;
    alignas(1) uint8_t industrial;
    alignas(1) uint8_t business;
    alignas(2) uint16_t envoy;
};
static_assert(sizeof(c2_save_CityCell_t) == 20, "struct size mismatch");

static inline const c2_save_CityCell_t *c2_save_CityCell__const_ptr_add(const c2_save_CityCell_t *p, size_t i) { return p + i; }
static inline c2_save_CityCell_t *c2_save_CityCell__ptr_add(c2_save_CityCell_t *p, size_t i) { return p + i; }
static inline c2_save_CityCell_struct_t c2_save_CityCell_vec_at(c2_save_CityCell_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t c2_save_CityCell__size(void) { return 20; }
static inline size_t c2_save_CityCell_vec_len(c2_save_CityCell_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(c2_save_CityCell)

__flatbuffers_define_struct_scalar_field(c2_save_CityCell, base_kind, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, terrain, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, road_aqueduct, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, edge_bits, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, extra_edge, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, activity_a, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, activity_b, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, building, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, range_flag, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, fpu_flag, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, entertainment, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, education, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, health, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, land_value, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, fire, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, security, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, industrial, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, business, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_CityCell, envoy, flatbuffers_uint16, uint16_t)

struct c2_save_Citizen {
    alignas(4) uint8_t exists;
    alignas(1) int8_t xp;
    alignas(1) int8_t type;
    alignas(1) int8_t world_dir;
    alignas(1) int8_t x;
    alignas(1) int8_t y;
    alignas(4) int32_t map_ref;
    alignas(1) uint8_t pixel_x;
    alignas(1) uint8_t pixel_y;
    alignas(1) int8_t dest_x;
    alignas(1) int8_t dest_y;
    alignas(1) uint8_t saved_state_idx;
    alignas(1) int8_t wait_count;
    alignas(1) int8_t state_idx;
    alignas(1) uint8_t wf_active;
    alignas(1) int8_t wf_step;
    alignas(1) int8_t wf_length;
    alignas(1) uint8_t wf_steps[8];
    alignas(1) int8_t speed;
    alignas(1) int8_t speed_count;
    alignas(1) int8_t speed_phase;
    alignas(1) int8_t flag_bits;
    alignas(1) uint8_t action_kind;
    alignas(1) uint8_t is_barbarian;
    alignas(1) int8_t state_timer;
    alignas(1) int8_t market_demand_a;
    alignas(1) int8_t market_demand_b;
    alignas(4) int32_t target_ref;
    alignas(2) uint16_t target;
    alignas(1) uint8_t target_count;
    alignas(2) int16_t evolve_timer;
    alignas(2) int16_t target_marker;
    alignas(1) uint8_t name_id;
    alignas(1) uint8_t state;
    alignas(2) int16_t image_id;
    alignas(1) uint8_t wobble_counter;
};
static_assert(sizeof(c2_save_Citizen_t) == 60, "struct size mismatch");

static inline const c2_save_Citizen_t *c2_save_Citizen__const_ptr_add(const c2_save_Citizen_t *p, size_t i) { return p + i; }
static inline c2_save_Citizen_t *c2_save_Citizen__ptr_add(c2_save_Citizen_t *p, size_t i) { return p + i; }
static inline c2_save_Citizen_struct_t c2_save_Citizen_vec_at(c2_save_Citizen_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t c2_save_Citizen__size(void) { return 60; }
static inline size_t c2_save_Citizen_vec_len(c2_save_Citizen_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(c2_save_Citizen)

__flatbuffers_define_struct_scalar_field(c2_save_Citizen, exists, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, xp, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, type, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, world_dir, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, x, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, y, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, map_ref, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, pixel_x, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, pixel_y, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, dest_x, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, dest_y, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, saved_state_idx, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, wait_count, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, state_idx, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, wf_active, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, wf_step, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, wf_length, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_fixed_array_field(c2_save_Citizen, wf_steps, flatbuffers_uint8, uint8_t, 8)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, speed, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, speed_count, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, speed_phase, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, flag_bits, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, action_kind, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, is_barbarian, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, state_timer, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, market_demand_a, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, market_demand_b, flatbuffers_int8, int8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, target_ref, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, target, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, target_count, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, evolve_timer, flatbuffers_int16, int16_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, target_marker, flatbuffers_int16, int16_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, name_id, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, state, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, image_id, flatbuffers_int16, int16_t)
__flatbuffers_define_struct_scalar_field(c2_save_Citizen, wobble_counter, flatbuffers_uint8, uint8_t)

struct c2_save_HistorySample {
    alignas(4) int32_t population;
    alignas(4) int32_t denarii;
    alignas(4) int32_t pop_tax;
    alignas(4) int32_t ind_tax;
    alignas(4) int32_t year;
};
static_assert(sizeof(c2_save_HistorySample_t) == 20, "struct size mismatch");

static inline const c2_save_HistorySample_t *c2_save_HistorySample__const_ptr_add(const c2_save_HistorySample_t *p, size_t i) { return p + i; }
static inline c2_save_HistorySample_t *c2_save_HistorySample__ptr_add(c2_save_HistorySample_t *p, size_t i) { return p + i; }
static inline c2_save_HistorySample_struct_t c2_save_HistorySample_vec_at(c2_save_HistorySample_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t c2_save_HistorySample__size(void) { return 20; }
static inline size_t c2_save_HistorySample_vec_len(c2_save_HistorySample_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(c2_save_HistorySample)

__flatbuffers_define_struct_scalar_field(c2_save_HistorySample, population, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(c2_save_HistorySample, denarii, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(c2_save_HistorySample, pop_tax, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(c2_save_HistorySample, ind_tax, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(c2_save_HistorySample, year, flatbuffers_int32, int32_t)


struct c2_save_Save_table { uint8_t unused__; };

static inline size_t c2_save_Save_vec_len(c2_save_Save_vec_t vec)
__flatbuffers_vec_len(vec)
static inline c2_save_Save_table_t c2_save_Save_vec_at(c2_save_Save_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(c2_save_Save_table_t, vec, i, 0)
__flatbuffers_table_as_root(c2_save_Save)

__flatbuffers_define_scalar_field(0, c2_save_Save, format_version, flatbuffers_uint32, uint32_t, UINT32_C(1))
__flatbuffers_define_string_field(1, c2_save_Save, engine_version, 0)
__flatbuffers_define_vector_field(2, c2_save_Save, scalars, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(3, c2_save_Save, city_map, c2_save_CityCell_vec_t, 0)
__flatbuffers_define_vector_field(4, c2_save_Save, region_map, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(5, c2_save_Save, battle_map, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(6, c2_save_Save, citizens, c2_save_Citizen_vec_t, 0)
__flatbuffers_define_vector_field(7, c2_save_Save, armies, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(8, c2_save_Save, army_routes, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(9, c2_save_Save, units, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(10, c2_save_Save, figures, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(11, c2_save_Save, figure_secondary_sprite, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(12, c2_save_Save, arrows, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(13, c2_save_Save, messages, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(14, c2_save_Save, fire_zones, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(15, c2_save_Save, industry, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(16, c2_save_Save, slave_requirements, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(17, c2_save_Save, history, c2_save_HistorySample_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* C2_SAVE_READER_H */
