#ifndef C2_SAVE_BUILDER_H
#define C2_SAVE_BUILDER_H

/* Generated by flatcc 0.6.3 FlatBuffers schema compiler for C by dvide.com */

#ifndef C2_SAVE_READER_H
#include "c2_save_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "C2SV"
#undef flatbuffers_extension
#define flatbuffers_extension "sav"

#define __c2_save_CityCell_formal_args ,\
  uint8_t v0, uint8_t v1, uint8_t v2, uint8_t v3,\
  uint8_t v4, uint8_t v5, uint8_t v6, uint8_t v7,\
  uint8_t v8, uint8_t v9, uint8_t v10, uint8_t v11,\
  uint8_t v12, uint8_t v13, uint8_t v14, uint8_t v15,\
  uint8_t v16, uint8_t v17, uint16_t v18
#define __c2_save_CityCell_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11,\
  v12, v13, v14, v15,\
  v16, v17, v18
static inline c2_save_CityCell_t *c2_save_CityCell_assign(c2_save_CityCell_t *p,
  uint8_t v0, uint8_t v1, uint8_t v2, uint8_t v3,
  uint8_t v4, uint8_t v5, uint8_t v6, uint8_t v7,
  uint8_t v8, uint8_t v9, uint8_t v10, uint8_t v11,
  uint8_t v12, uint8_t v13, uint8_t v14, uint8_t v15,
  uint8_t v16, uint8_t v17, uint16_t v18)
{ p->base_kind = v0; p->terrain = v1; p->road_aqueduct = v2; p->edge_bits = v3;
  p->extra_edge = v4; p->activity_a = v5; p->activity_b = v6; p->building = v7;
  p->range_flag = v8; p->fpu_flag = v9; p->entertainment = v10; p->education = v11;
  p->health = v12; p->land_value = v13; p->fire = v14; p->security = v15;
  p->industrial = v16; p->business = v17; p->envoy = v18;
  return p; }
static inline c2_save_CityCell_t *c2_save_CityCell_copy(c2_save_CityCell_t *p, const c2_save_CityCell_t *p2)
{ p->base_kind = p2->base_kind; p->terrain = p2->terrain; p->road_aqueduct = p2->road_aqueduct; p->edge_bits = p2->edge_bits;
  p->extra_edge = p2->extra_edge; p->activity_a = p2->activity_a; p->activity_b = p2->activity_b; p->building = p2->building;
  p->range_flag = p2->range_flag; p->fpu_flag = p2->fpu_flag; p->entertainment = p2->entertainment; p->education = p2->education;
  p->health = p2->health; p->land_value = p2->land_value; p->fire = p2->fire; p->security = p2->security;
  p->industrial = p2->industrial; p->business = p2->business; p->envoy = p2->envoy;
  return p; }
static inline c2_save_CityCell_t *c2_save_CityCell_assign_to_pe(c2_save_CityCell_t *p,
  uint8_t v0, uint8_t v1, uint8_t v2, uint8_t v3,
  uint8_t v4, uint8_t v5, uint8_t v6, uint8_t v7,
  uint8_t v8, uint8_t v9, uint8_t v10, uint8_t v11,
  uint8_t v12, uint8_t v13, uint8_t v14, uint8_t v15,
  uint8_t v16, uint8_t v17, uint16_t v18)
{ p->base_kind = v0; p->terrain = v1; p->road_aqueduct = v2; p->edge_bits = v3;
  p->extra_edge = v4; p->activity_a = v5; p->activity_b = v6; p->building = v7;
  p->range_flag = v8; p->fpu_flag = v9; p->entertainment = v10; p->education = v11;
  p->health = v12; p->land_value = v13; p->fire = v14; p->security = v15;
  p->industrial = v16; p->business = v17; flatbuffers_uint16_assign_to_pe(&p->envoy, v18);
  return p; }
static inline c2_save_CityCell_t *c2_save_CityCell_copy_to_pe(c2_save_CityCell_t *p, const c2_save_CityCell_t *p2)
{ p->base_kind = p2->base_kind; p->terrain = p2->terrain; p->road_aqueduct = p2->road_aqueduct; p->edge_bits = p2->edge_bits;
  p->extra_edge = p2->extra_edge; p->activity_a = p2->activity_a; p->activity_b = p2->activity_b; p->building = p2->building;
  p->range_flag = p2->range_flag; p->fpu_flag = p2->fpu_flag; p->entertainment = p2->entertainment; p->education = p2->education;
  p->health = p2->health; p->land_value = p2->land_value; p->fire = p2->fire; p->security = p2->security;
  p->industrial = p2->industrial; p->business = p2->business; flatbuffers_uint16_copy_to_pe(&p->envoy, &p2->envoy);
  return p; }
static inline c2_save_CityCell_t *c2_save_CityCell_assign_from_pe(c2_save_CityCell_t *p,
  uint8_t v0, uint8_t v1, uint8_t v2, uint8_t v3,
  uint8_t v4, uint8_t v5, uint8_t v6, uint8_t v7,
  uint8_t v8, uint8_t v9, uint8_t v10, uint8_t v11,
  uint8_t v12, uint8_t v13, uint8_t v14, uint8_t v15,
  uint8_t v16, uint8_t v17, uint16_t v18)
{ p->base_kind = v0; p->terrain = v1; p->road_aqueduct = v2; p->edge_bits = v3;
  p->extra_edge = v4; p->activity_a = v5; p->activity_b = v6; p->building = v7;
  p->range_flag = v8; p->fpu_flag = v9; p->entertainment = v10; p->education = v11;
  p->health = v12; p->land_value = v13; p->fire = v14; p->security = v15;
  p->industrial = v16; p->business = v17; flatbuffers_uint16_assign_from_pe(&p->envoy, v18);
  return p; }
static inline c2_save_CityCell_t *c2_save_CityCell_copy_from_pe(c2_save_CityCell_t *p, const c2_save_CityCell_t *p2)
{ p->base_kind = p2->base_kind; p->terrain = p2->terrain; p->road_aqueduct = p2->road_aqueduct; p->edge_bits = p2->edge_bits;
  p->extra_edge = p2->extra_edge; p->activity_a = p2->activity_a; p->activity_b = p2->activity_b; p->building = p2->building;
  p->range_flag = p2->range_flag; p->fpu_flag = p2->fpu_flag; p->entertainment = p2->entertainment; p->education = p2->education;
  p->health = p2->health; p->land_value = p2->land_value; p->fire = p2->fire; p->security = p2->security;
  p->industrial = p2->industrial; p->business = p2->business; flatbuffers_uint16_copy_from_pe(&p->envoy, &p2->envoy);
  return p; }
__flatbuffers_build_struct(flatbuffers_, c2_save_CityCell, 20, 2, c2_save_CityCell_file_identifier, c2_save_CityCell_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, c2_save_CityCell, c2_save_CityCell_t)

#define __c2_save_Citizen_formal_args ,\
  uint8_t v0, int8_t v1, int8_t v2, int8_t v3,\
  int8_t v4, int8_t v5, int32_t v6, uint8_t v7,\
  uint8_t v8, int8_t v9, int8_t v10, uint8_t v11,\
  int8_t v12, int8_t v13, uint8_t v14, int8_t v15,\
  int8_t v16, const uint8_t v17[8], int8_t v18, int8_t v19,\
  int8_t v20, int8_t v21, uint8_t v22, uint8_t v23,\
  int8_t v24, int8_t v25, int8_t v26, int32_t v27,\
  uint16_t v28, uint8_t v29, int16_t v30, int16_t v31,\
  uint8_t v32, uint8_t v33, int16_t v34, uint8_t v35
#define __c2_save_Citizen_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11,\
  v12, v13, v14, v15,\
  v16, v17, v18, v19,\
  v20, v21, v22, v23,\
  v24, v25, v26, v27,\
  v28, v29, v30, v31,\
  v32, v33, v34, v35
static inline c2_save_Citizen_t *c2_save_Citizen_assign(c2_save_Citizen_t *p,
  uint8_t v0, int8_t v1, int8_t v2, int8_t v3,
  int8_t v4, int8_t v5, int32_t v6, uint8_t v7,
  uint8_t v8, int8_t v9, int8_t v10, uint8_t v11,
  int8_t v12, int8_t v13, uint8_t v14, int8_t v15,
  int8_t v16, const uint8_t v17[8], int8_t v18, int8_t v19,
  int8_t v20, int8_t v21, uint8_t v22, uint8_t v23,
  int8_t v24, int8_t v25, int8_t v26, int32_t v27,
  uint16_t v28, uint8_t v29, int16_t v30, int16_t v31,
  uint8_t v32, uint8_t v33, int16_t v34, uint8_t v35)
{ p->exists = v0; p->xp = v1; p->type = v2; p->world_dir = v3;
  p->x = v4; p->y = v5; p->map_ref = v6; p->pixel_x = v7;
  p->pixel_y = v8; p->dest_x = v9; p->dest_y = v10; p->saved_state_idx = v11;
  p->wait_count = v12; p->state_idx = v13; p->wf_active = v14; p->wf_step = v15;
  p->wf_length = v16; flatbuffers_uint8_array_copy(p->wf_steps, v17, 8); p->speed = v18; p->speed_count = v19;
  p->speed_phase = v20; p->flag_bits = v21; p->action_kind = v22; p->is_barbarian = v23;
  p->state_timer = v24; p->market_demand_a = v25; p->market_demand_b = v26; p->target_ref = v27;
  p->target = v28; p->target_count = v29; p->evolve_timer = v30; p->target_marker = v31;
  p->name_id = v32; p->state = v33; p->image_id = v34; p->wobble_counter = v35;
  return p; }
static inline c2_save_Citizen_t *c2_save_Citizen_copy(c2_save_Citizen_t *p, const c2_save_Citizen_t *p2)
{ p->exists = p2->exists; p->xp = p2->xp; p->type = p2->type; p->world_dir = p2->world_dir;
  p->x = p2->x; p->y = p2->y; p->map_ref = p2->map_ref; p->pixel_x = p2->pixel_x;
  p->pixel_y = p2->pixel_y; p->dest_x = p2->dest_x; p->dest_y = p2->dest_y; p->saved_state_idx = p2->saved_state_idx;
  p->wait_count = p2->wait_count; p->state_idx = p2->state_idx; p->wf_active = p2->wf_active; p->wf_step = p2->wf_step;
  p->wf_length = p2->wf_length; flatbuffers_uint8_array_copy(p->wf_steps, p2->wf_steps, 8); p->speed = p2->speed; p->speed_count = p2->speed_count;
  p->speed_phase = p2->speed_phase; p->flag_bits = p2->flag_bits; p->action_kind = p2->action_kind; p->is_barbarian = p2->is_barbarian;
  p->state_timer = p2->state_timer; p->market_demand_a = p2->market_demand_a; p->market_demand_b = p2->market_demand_b; p->target_ref = p2->target_ref;
  p->target = p2->target; p->target_count = p2->target_count; p->evolve_timer = p2->evolve_timer; p->target_marker = p2->target_marker;
  p->name_id = p2->name_id; p->state = p2->state; p->image_id = p2->image_id; p->wobble_counter = p2->wobble_counter;
  return p; }
static inline c2_save_Citizen_t *c2_save_Citizen_assign_to_pe(c2_save_Citizen_t *p,
  uint8_t v0, int8_t v1, int8_t v2, int8_t v3,
  int8_t v4, int8_t v5, int32_t v6, uint8_t v7,
  uint8_t v8, int8_t v9, int8_t v10, uint8_t v11,
  int8_t v12, int8_t v13, uint8_t v14, int8_t v15,
  int8_t v16, const uint8_t v17[8], int8_t v18, int8_t v19,
  int8_t v20, int8_t v21, uint8_t v22, uint8_t v23,
  int8_t v24, int8_t v25, int8_t v26, int32_t v27,
  uint16_t v28, uint8_t v29, int16_t v30, int16_t v31,
  uint8_t v32, uint8_t v33, int16_t v34, uint8_t v35)
{ p->exists = v0; p->xp = v1; p->type = v2; p->world_dir = v3;
  p->x = v4; p->y = v5; flatbuffers_int32_assign_to_pe(&p->map_ref, v6); p->pixel_x = v7;
  p->pixel_y = v8; p->dest_x = v9; p->dest_y = v10; p->saved_state_idx = v11;
  p->wait_count = v12; p->state_idx = v13; p->wf_active = v14; p->wf_step = v15;
  p->wf_length = v16; flatbuffers_uint8_array_copy_to_pe(p->wf_steps, v17, 8); p->speed = v18; p->speed_count = v19;
  p->speed_phase = v20; p->flag_bits = v21; p->action_kind = v22; p->is_barbarian = v23;
  p->state_timer = v24; p->market_demand_a = v25; p->market_demand_b = v26; flatbuffers_int32_assign_to_pe(&p->target_ref, v27);
  flatbuffers_uint16_assign_to_pe(&p->target, v28); p->target_count = v29; flatbuffers_int16_assign_to_pe(&p->evolve_timer, v30); flatbuffers_int16_assign_to_pe(&p->target_marker, v31);
  p->name_id = v32; p->state = v33; flatbuffers_int16_assign_to_pe(&p->image_id, v34); p->wobble_counter = v35;
  return p; }
static inline c2_save_Citizen_t *c2_save_Citizen_copy_to_pe(c2_save_Citizen_t *p, const c2_save_Citizen_t *p2)
{ p->exists = p2->exists; p->xp = p2->xp; p->type = p2->type; p->world_dir = p2->world_dir;
  p->x = p2->x; p->y = p2->y; flatbuffers_int32_copy_to_pe(&p->map_ref, &p2->map_ref); p->pixel_x = p2->pixel_x;
  p->pixel_y = p2->pixel_y; p->dest_x = p2->dest_x; p->dest_y = p2->dest_y; p->saved_state_idx = p2->saved_state_idx;
  p->wait_count = p2->wait_count; p->state_idx = p2->state_idx; p->wf_active = p2->wf_active; p->wf_step = p2->wf_step;
  p->wf_length = p2->wf_length; flatbuffers_uint8_array_copy_to_pe(p->wf_steps, p2->wf_steps, 8); p->speed = p2->speed; p->speed_count = p2->speed_count;
  p->speed_phase = p2->speed_phase; p->flag_bits = p2->flag_bits; p->action_kind = p2->action_kind; p->is_barbarian = p2->is_barbarian;
  p->state_timer = p2->state_timer; p->market_demand_a = p2->market_demand_a; p->market_demand_b = p2->market_demand_b; flatbuffers_int32_copy_to_pe(&p->target_ref, &p2->target_ref);
  flatbuffers_uint16_copy_to_pe(&p->target, &p2->target); p->target_count = p2->target_count; flatbuffers_int16_copy_to_pe(&p->evolve_timer, &p2->evolve_timer); flatbuffers_int16_copy_to_pe(&p->target_marker, &p2->target_marker);
  p->name_id = p2->name_id; p->state = p2->state; flatbuffers_int16_copy_to_pe(&p->image_id, &p2->image_id); p->wobble_counter = p2->wobble_counter;
  return p; }
static inline c2_save_Citizen_t *c2_save_Citizen_assign_from_pe(c2_save_Citizen_t *p,
  uint8_t v0, int8_t v1, int8_t v2, int8_t v3,
  int8_t v4, int8_t v5, int32_t v6, uint8_t v7,
  uint8_t v8, int8_t v9, int8_t v10, uint8_t v11,
  int8_t v12, int8_t v13, uint8_t v14, int8_t v15,
  int8_t v16, const uint8_t v17[8], int8_t v18, int8_t v19,
  int8_t v20, int8_t v21, uint8_t v22, uint8_t v23,
  int8_t v24, int8_t v25, int8_t v26, int32_t v27,
  uint16_t v28, uint8_t v29, int16_t v30, int16_t v31,
  uint8_t v32, uint8_t v33, int16_t v34, uint8_t v35)
{ p->exists = v0; p->xp = v1; p->type = v2; p->world_dir = v3;
  p->x = v4; p->y = v5; flatbuffers_int32_assign_from_pe(&p->map_ref, v6); p->pixel_x = v7;
  p->pixel_y = v8; p->dest_x = v9; p->dest_y = v10; p->saved_state_idx = v11;
  p->wait_count = v12; p->state_idx = v13; p->wf_active = v14; p->wf_step = v15;
  p->wf_length = v16; flatbuffers_uint8_array_copy_from_pe(p->wf_steps, v17, 8); p->speed = v18; p->speed_count = v19;
  p->speed_phase = v20; p->flag_bits = v21; p->action_kind = v22; p->is_barbarian = v23;
  p->state_timer = v24; p->market_demand_a = v25; p->market_demand_b = v26; flatbuffers_int32_assign_from_pe(&p->target_ref, v27);
  flatbuffers_uint16_assign_from_pe(&p->target, v28); p->target_count = v29; flatbuffers_int16_assign_from_pe(&p->evolve_timer, v30); flatbuffers_int16_assign_from_pe(&p->target_marker, v31);
  p->name_id = v32; p->state = v33; flatbuffers_int16_assign_from_pe(&p->image_id, v34); p->wobble_counter = v35;
  return p; }
static inline c2_save_Citizen_t *c2_save_Citizen_copy_from_pe(c2_save_Citizen_t *p, const c2_save_Citizen_t *p2)
{ p->exists = p2->exists; p->xp = p2->xp; p->type = p2->type; p->world_dir = p2->world_dir;
  p->x = p2->x; p->y = p2->y; flatbuffers_int32_copy_from_pe(&p->map_ref, &p2->map_ref); p->pixel_x = p2->pixel_x;
  p->pixel_y = p2->pixel_y; p->dest_x = p2->dest_x; p->dest_y = p2->dest_y; p->saved_state_idx = p2->saved_state_idx;
  p->wait_count = p2->wait_count; p->state_idx = p2->state_idx; p->wf_active = p2->wf_active; p->wf_step = p2->wf_step;
  p->wf_length = p2->wf_length; flatbuffers_uint8_array_copy_from_pe(p->wf_steps, p2->wf_steps, 8); p->speed = p2->speed; p->speed_count = p2->speed_count;
  p->speed_phase = p2->speed_phase; p->flag_bits = p2->flag_bits; p->action_kind = p2->action_kind; p->is_barbarian = p2->is_barbarian;
  p->state_timer = p2->state_timer; p->market_demand_a = p2->market_demand_a; p->market_demand_b = p2->market_demand_b; flatbuffers_int32_copy_from_pe(&p->target_ref, &p2->target_ref);
  flatbuffers_uint16_copy_from_pe(&p->target, &p2->target); p->target_count = p2->target_count; flatbuffers_int16_copy_from_pe(&p->evolve_timer, &p2->evolve_timer); flatbuffers_int16_copy_from_pe(&p->target_marker, &p2->target_marker);
  p->name_id = p2->name_id; p->state = p2->state; flatbuffers_int16_copy_from_pe(&p->image_id, &p2->image_id); p->wobble_counter = p2->wobble_counter;
  return p; }
__flatbuffers_build_struct(flatbuffers_, c2_save_Citizen, 60, 4, c2_save_Citizen_file_identifier, c2_save_Citizen_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, c2_save_Citizen, c2_save_Citizen_t)

#define __c2_save_HistorySample_formal_args ,\
  int32_t v0, int32_t v1, int32_t v2, int32_t v3, int32_t v4
#define __c2_save_HistorySample_call_args ,\
  v0, v1, v2, v3, v4
static inline c2_save_HistorySample_t *c2_save_HistorySample_assign(c2_save_HistorySample_t *p,
  int32_t v0, int32_t v1, int32_t v2, int32_t v3, int32_t v4)
{ p->population = v0; p->denarii = v1; p->pop_tax = v2; p->ind_tax = v3;
  p->year = v4;
  return p; }
static inline c2_save_HistorySample_t *c2_save_HistorySample_copy(c2_save_HistorySample_t *p, const c2_save_HistorySample_t *p2)
{ p->population = p2->population; p->denarii = p2->denarii; p->pop_tax = p2->pop_tax; p->ind_tax = p2->ind_tax;
  p->year = p2->year;
  return p; }
static inline c2_save_HistorySample_t *c2_save_HistorySample_assign_to_pe(c2_save_HistorySample_t *p,
  int32_t v0, int32_t v1, int32_t v2, int32_t v3, int32_t v4)
{ flatbuffers_int32_assign_to_pe(&p->population, v0); flatbuffers_int32_assign_to_pe(&p->denarii, v1); flatbuffers_int32_assign_to_pe(&p->pop_tax, v2); flatbuffers_int32_assign_to_pe(&p->ind_tax, v3);
  flatbuffers_int32_assign_to_pe(&p->year, v4);
  return p; }
static inline c2_save_HistorySample_t *c2_save_HistorySample_copy_to_pe(c2_save_HistorySample_t *p, const c2_save_HistorySample_t *p2)
{ flatbuffers_int32_copy_to_pe(&p->population, &p2->population); flatbuffers_int32_copy_to_pe(&p->denarii, &p2->denarii); flatbuffers_int32_copy_to_pe(&p->pop_tax, &p2->pop_tax); flatbuffers_int32_copy_to_pe(&p->ind_tax, &p2->ind_tax);
  flatbuffers_int32_copy_to_pe(&p->year, &p2->year);
  return p; }
static inline c2_save_HistorySample_t *c2_save_HistorySample_assign_from_pe(c2_save_HistorySample_t *p,
  int32_t v0, int32_t v1, int32_t v2, int32_t v3, int32_t v4)
{ flatbuffers_int32_assign_from_pe(&p->population, v0); flatbuffers_int32_assign_from_pe(&p->denarii, v1); flatbuffers_int32_assign_from_pe(&p->pop_tax, v2); flatbuffers_int32_assign_from_pe(&p->ind_tax, v3);
  flatbuffers_int32_assign_from_pe(&p->year, v4);
  return p; }
static inline c2_save_HistorySample_t *c2_save_HistorySample_copy_from_pe(c2_save_HistorySample_t *p, const c2_save_HistorySample_t *p2)
{ flatbuffers_int32_copy_from_pe(&p->population, &p2->population); flatbuffers_int32_copy_from_pe(&p->denarii, &p2->denarii); flatbuffers_int32_copy_from_pe(&p->pop_tax, &p2->pop_tax); flatbuffers_int32_copy_from_pe(&p->ind_tax, &p2->ind_tax);
  flatbuffers_int32_copy_from_pe(&p->year, &p2->year);
  return p; }
__flatbuffers_build_struct(flatbuffers_, c2_save_HistorySample, 20, 4, c2_save_HistorySample_file_identifier, c2_save_HistorySample_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, c2_save_HistorySample, c2_save_HistorySample_t)

static const flatbuffers_voffset_t __c2_save_Save_required[] = { 0 };
typedef flatbuffers_ref_t c2_save_Save_ref_t;
static c2_save_Save_ref_t c2_save_Save_clone(flatbuffers_builder_t *B, c2_save_Save_table_t t);
__flatbuffers_build_table(flatbuffers_, c2_save_Save, 18)

#define __c2_save_Save_formal_args ,\
  uint32_t v0, flatbuffers_string_ref_t v1, flatbuffers_uint8_vec_ref_t v2, c2_save_CityCell_vec_ref_t v3,\
  flatbuffers_uint8_vec_ref_t v4, flatbuffers_uint8_vec_ref_t v5, c2_save_Citizen_vec_ref_t v6, flatbuffers_uint8_vec_ref_t v7,\
  flatbuffers_uint8_vec_ref_t v8, flatbuffers_uint8_vec_ref_t v9, flatbuffers_uint8_vec_ref_t v10, flatbuffers_bool_vec_ref_t v11,\
  flatbuffers_uint8_vec_ref_t v12, flatbuffers_uint8_vec_ref_t v13, flatbuffers_uint8_vec_ref_t v14, flatbuffers_uint8_vec_ref_t v15, flatbuffers_uint8_vec_ref_t v16, c2_save_HistorySample_vec_ref_t v17
#define __c2_save_Save_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11,\
  v12, v13, v14, v15, v16, v17
static inline c2_save_Save_ref_t c2_save_Save_create(flatbuffers_builder_t *B __c2_save_Save_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, c2_save_Save, c2_save_Save_file_identifier, c2_save_Save_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, c2_save_Save_format_version, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(1), c2_save_Save)
__flatbuffers_build_string_field(1, flatbuffers_, c2_save_Save_engine_version, c2_save_Save)
__flatbuffers_build_vector_field(2, flatbuffers_, c2_save_Save_scalars, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(3, flatbuffers_, c2_save_Save_city_map, c2_save_CityCell, c2_save_CityCell_t, c2_save_Save)
__flatbuffers_build_vector_field(4, flatbuffers_, c2_save_Save_region_map, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(5, flatbuffers_, c2_save_Save_battle_map, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(6, flatbuffers_, c2_save_Save_citizens, c2_save_Citizen, c2_save_Citizen_t, c2_save_Save)
__flatbuffers_build_vector_field(7, flatbuffers_, c2_save_Save_armies, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(8, flatbuffers_, c2_save_Save_army_routes, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(9, flatbuffers_, c2_save_Save_units, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(10, flatbuffers_, c2_save_Save_figures, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(11, flatbuffers_, c2_save_Save_figure_secondary_sprite, flatbuffers_bool, flatbuffers_bool_t, c2_save_Save)
__flatbuffers_build_vector_field(12, flatbuffers_, c2_save_Save_arrows, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(13, flatbuffers_, c2_save_Save_messages, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(14, flatbuffers_, c2_save_Save_fire_zones, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(15, flatbuffers_, c2_save_Save_industry, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(16, flatbuffers_, c2_save_Save_slave_requirements, flatbuffers_uint8, uint8_t, c2_save_Save)
__flatbuffers_build_vector_field(17, flatbuffers_, c2_save_Save_history, c2_save_HistorySample, c2_save_HistorySample_t, c2_save_Save)

static inline c2_save_Save_ref_t c2_save_Save_create(flatbuffers_builder_t *B __c2_save_Save_formal_args)
{
    if (c2_save_Save_start(B)
        || c2_save_Save_format_version_add(B, v0)
        || c2_save_Save_engine_version_add(B, v1)
        || c2_save_Save_scalars_add(B, v2)
        || c2_save_Save_city_map_add(B, v3)
        || c2_save_Save_region_map_add(B, v4)
        || c2_save_Save_battle_map_add(B, v5)
        || c2_save_Save_citizens_add(B, v6)
        || c2_save_Save_armies_add(B, v7)
        || c2_save_Save_army_routes_add(B, v8)
        || c2_save_Save_units_add(B, v9)
        || c2_save_Save_figures_add(B, v10)
        || c2_save_Save_figure_secondary_sprite_add(B, v11)
        || c2_save_Save_arrows_add(B, v12)
        || c2_save_Save_messages_add(B, v13)
        || c2_save_Save_fire_zones_add(B, v14)
        || c2_save_Save_industry_add(B, v15)
        || c2_save_Save_slave_requirements_add(B, v16)
        || c2_save_Save_history_add(B, v17)) {
        return 0;
    }
    return c2_save_Save_end(B);
}

static c2_save_Save_ref_t c2_save_Save_clone(flatbuffers_builder_t *B, c2_save_Save_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (c2_save_Save_start(B)
        || c2_save_Save_format_version_pick(B, t)
        || c2_save_Save_engine_version_pick(B, t)
        || c2_save_Save_scalars_pick(B, t)
        || c2_save_Save_city_map_pick(B, t)
        || c2_save_Save_region_map_pick(B, t)
        || c2_save_Save_battle_map_pick(B, t)
        || c2_save_Save_citizens_pick(B, t)
        || c2_save_Save_armies_pick(B, t)
        || c2_save_Save_army_routes_pick(B, t)
        || c2_save_Save_units_pick(B, t)
        || c2_save_Save_figures_pick(B, t)
        || c2_save_Save_figure_secondary_sprite_pick(B, t)
        || c2_save_Save_arrows_pick(B, t)
        || c2_save_Save_messages_pick(B, t)
        || c2_save_Save_fire_zones_pick(B, t)
        || c2_save_Save_industry_pick(B, t)
        || c2_save_Save_slave_requirements_pick(B, t)
        || c2_save_Save_history_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, c2_save_Save_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* C2_SAVE_BUILDER_H */
