#ifndef C2_SAVE_VERIFIER_H
#define C2_SAVE_VERIFIER_H

/* Generated by flatcc 0.6.3 FlatBuffers schema compiler for C by dvide.com */

#ifndef C2_SAVE_READER_H
#include "c2_save_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int c2_save_Save_verify_table(flatcc_table_verifier_descriptor_t *td);

static inline int c2_save_CityCell_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, c2_save_CityCell_identifier, 20, 2);
}

static inline int c2_save_CityCell_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, c2_save_CityCell_identifier, 20, 2);
}

static inline int c2_save_CityCell_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, c2_save_CityCell_type_hash, 20, 2);
}

static inline int c2_save_CityCell_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, c2_save_CityCell_type_hash, 20, 2);
}

static inline int c2_save_CityCell_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 20, 2);
}

static inline int c2_save_CityCell_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 20, 2);
}

static inline int c2_save_CityCell_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 20, 2);
}

static inline int c2_save_CityCell_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 20, 2);
}

static inline int c2_save_Citizen_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, c2_save_Citizen_identifier, 60, 4);
}

static inline int c2_save_Citizen_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, c2_save_Citizen_identifier, 60, 4);
}

static inline int c2_save_Citizen_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, c2_save_Citizen_type_hash, 60, 4);
}

static inline int c2_save_Citizen_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, c2_save_Citizen_type_hash, 60, 4);
}

static inline int c2_save_Citizen_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 60, 4);
}

static inline int c2_save_Citizen_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 60, 4);
}

static inline int c2_save_Citizen_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 60, 4);
}

static inline int c2_save_Citizen_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 60, 4);
}

static inline int c2_save_HistorySample_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, c2_save_HistorySample_identifier, 20, 4);
}

static inline int c2_save_HistorySample_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, c2_save_HistorySample_identifier, 20, 4);
}

static inline int c2_save_HistorySample_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, c2_save_HistorySample_type_hash, 20, 4);
}

static inline int c2_save_HistorySample_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, c2_save_HistorySample_type_hash, 20, 4);
}

static inline int c2_save_HistorySample_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 20, 4);
}

static inline int c2_save_HistorySample_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 20, 4);
}

static inline int c2_save_HistorySample_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 20, 4);
}

static inline int c2_save_HistorySample_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 20, 4);
}

static int c2_save_Save_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* format_version */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* engine_version */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 2, 0, 1, 1, INT64_C(4294967295)) /* scalars */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 3, 0, 20, 2, INT64_C(214748364)) /* city_map */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 4, 0, 1, 1, INT64_C(4294967295)) /* region_map */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 5, 0, 1, 1, INT64_C(4294967295)) /* battle_map */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 6, 0, 60, 4, INT64_C(71582788)) /* citizens */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 7, 0, 1, 1, INT64_C(4294967295)) /* armies */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 8, 0, 1, 1, INT64_C(4294967295)) /* army_routes */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 9, 0, 1, 1, INT64_C(4294967295)) /* units */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 10, 0, 1, 1, INT64_C(4294967295)) /* figures */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 11, 0, 1, 1, INT64_C(4294967295)) /* figure_secondary_sprite */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 12, 0, 1, 1, INT64_C(4294967295)) /* arrows */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 13, 0, 1, 1, INT64_C(4294967295)) /* messages */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 14, 0, 1, 1, INT64_C(4294967295)) /* fire_zones */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 15, 0, 1, 1, INT64_C(4294967295)) /* industry */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 16, 0, 1, 1, INT64_C(4294967295)) /* slave_requirements */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 17, 0, 20, 4, INT64_C(214748364)) /* history */)) return ret;
    return flatcc_verify_ok;
}

static inline int c2_save_Save_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, c2_save_Save_identifier, &c2_save_Save_verify_table);
}

static inline int c2_save_Save_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, c2_save_Save_identifier, &c2_save_Save_verify_table);
}

static inline int c2_save_Save_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, c2_save_Save_type_identifier, &c2_save_Save_verify_table);
}

static inline int c2_save_Save_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, c2_save_Save_type_identifier, &c2_save_Save_verify_table);
}

static inline int c2_save_Save_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &c2_save_Save_verify_table);
}

static inline int c2_save_Save_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &c2_save_Save_verify_table);
}

static inline int c2_save_Save_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &c2_save_Save_verify_table);
}

static inline int c2_save_Save_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &c2_save_Save_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* C2_SAVE_VERIFIER_H */
