
#include "pcsound.h"
#include "c2_data.h"

struct speech_file_rec speech_files[104] = {
    { "a01.raw" },
    { "a02.raw" },
    { "a03.raw" },
    { "a04.raw" },
    { "a05.raw" },
    { "a06.raw" },
    { "a07.raw" },
    { "a08.raw" },
    { "a09.raw" },
    { "a10.raw" },
    { "a11.raw" },
    { "a12.raw" },
    { "a13.raw" },
    { "a14.raw" },
    { "a15.raw" },
    { "a16.raw" },
    { "a17.raw" },
    { "a18.raw" },
    { "a19.raw" },
    { "a20.raw" },
    { "a21.raw" },
    { "a22.raw" },
    { "a23.raw" },
    { "a24.raw" },
    { "a25.raw" },
    { "a26.raw" },
    { "a27.raw" },
    { "a28.raw" },
    { "a29.raw" },
    { "a30.raw" },
    { "b01.raw" },
    { "b02.raw" },
    { "b03.raw" },
    { "b04.raw" },
    { "b05.raw" },
    { "b06.raw" },
    { "b07.raw" },
    { "b08.raw" },
    { "b09.raw" },
    { "b10.raw" },
    { "b11.raw" },
    { "b12.raw" },
    { "b13.raw" },
    { "b14.raw" },
    { "b15.raw" },
    { "b16.raw" },
    { "b17.raw" },
    { "b18.raw" },
    { "b19.raw" },
    { "b20.raw" },
    { "b21.raw" },
    { "b22.raw" },
    { "b23.raw" },
    { "b24.raw" },
    { "b25.raw" },
    { "b26.raw" },
    { "b27.raw" },
    { "b28.raw" },
    { "b29.raw" },
    { "b30.raw" },
    { "c01.raw" },
    { "c02.raw" },
    { "c03.raw" },
    { "c04.raw" },
    { "c05.raw" },
    { "c06.raw" },
    { "c07.raw" },
    { "c08.raw" },
    { "c09.raw" },
    { "c10.raw" },
    { "c11.raw" },
    { "c12.raw" },
    { "c13.raw" },
    { "c14.raw" },
    { "c15.raw" },
    { "c16.raw" },
    { "c17.raw" },
    { "c18.raw" },
    { "c19.raw" },
    { "c20.raw" },
    { "c21.raw" },
    { "c22.raw" },
    { "c23.raw" },
    { "c24.raw" },
    { "c25.raw" },
    { "c26.raw" },
    { "c27.raw" },
    { "c28.raw" },
    { "c29.raw" },
    { "c30.raw" },
    { "c31.raw" },
    { "c32.raw" },
    { "c33.raw" },
    { "c34.raw" },
    { "c35.raw" },
    { "c36.raw" },
    { "c37.raw" },
    { "c38.raw" },
    { "c39.raw" },
    { "c40.raw" },
    { "c41.raw" },
    { "c42.raw" },
    { "c43.raw" },
    { "c44.raw" }
};

/* Filename of the speech sample selected for playback. */
char *speech_filaname;


// Selects an indexed speech sample and passes it to the streaming audio player.
// FUNCTION: C2 0x135a4
// FUNCTION: C2WIN 0x00482a90
void play_speech(int speech_idx) {
    speech_filaname = speech_files[speech_idx].name;
    set_db_sound(speech_filaname);
}
