# Embed the gettext files in po/ as C arrays.
#
#   cmake -DOUTPUT=<file.c> -DINPUTS="a.pot;b.po" -P EmbedText.cmake
#
# Each file becomes one array; the language tag is the file's stem, except
# that the template (.pot) is English. The table c2_text_bundle[] lists them
# in the order given, so put the template first.

if(NOT OUTPUT OR NOT INPUTS)
    message(FATAL_ERROR "EmbedText.cmake needs OUTPUT and INPUTS")
endif()

set(content "/* Generated by cmake/EmbedText.cmake from po/. Do not edit. */\n")
string(APPEND content "#include \"c2_port_text.h\"\n\n")
set(table "")
set(count 0)
foreach(input IN LISTS INPUTS)
    get_filename_component(stem "${input}" NAME_WE)
    get_filename_component(ext "${input}" EXT)
    if(ext STREQUAL ".pot")
        set(tag "en")
    else()
        set(tag "${stem}")
    endif()
    string(MAKE_C_IDENTIFIER "c2_po_${tag}" symbol)
    file(READ "${input}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    math(EXPR size "${hex_length} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "(0x[0-9a-f][0-9a-f],){24}" "\\0\n" bytes "${bytes}")
    string(APPEND content "static const unsigned char ${symbol}[] = {\n${bytes}\n};\n\n")
    string(APPEND table "    { \"${tag}\", ${symbol}, ${size} },\n")
    math(EXPR count "${count} + 1")
endforeach()
string(APPEND content "const struct c2_text_bundle_entry c2_text_bundle[] = {\n${table}};\n")
string(APPEND content "const int c2_text_bundle_count = ${count};\n")
file(WRITE "${OUTPUT}.tmp" "${content}")
file(RENAME "${OUTPUT}.tmp" "${OUTPUT}")
