# Embed one file as a C array.
#
#   cmake -DOUTPUT=<file.c> -DINPUT=<file> -DSYMBOL=<name> -P EmbedFile.cmake
#
# Writes `const unsigned char <name>[]` and `const unsigned int <name>_size`.

if(NOT OUTPUT OR NOT INPUT OR NOT SYMBOL)
    message(FATAL_ERROR "EmbedFile.cmake needs OUTPUT, INPUT and SYMBOL")
endif()

file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hex_length)
math(EXPR size "${hex_length} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
string(REGEX REPLACE "(0x[0-9a-f][0-9a-f],){24}" "\\0\n" bytes "${bytes}")
get_filename_component(name "${INPUT}" NAME)
set(content "/* Generated by cmake/EmbedFile.cmake from ${name}. Do not edit. */\n")
string(APPEND content "const unsigned char ${SYMBOL}[] = {\n${bytes}\n};\n")
string(APPEND content "const unsigned int ${SYMBOL}_size = ${size}u;\n")
file(WRITE "${OUTPUT}.tmp" "${content}")
file(RENAME "${OUTPUT}.tmp" "${OUTPUT}")
